//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: transfer_hook
// ----------------------------------------------------------------------------
pub mod transfer_hook {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for transfer_hook
    pub fn program_id() -> Pubkey {
        pubkey!("Fsg5gXrxo5Spx3ffMHVRpGsi919U141fWrd5EDo96iw2")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: InitializeExtraAccountMetaList
    // ....................................................................

    /// Main instruction struct for InitializeExtraAccountMetaList
    pub struct InitializeExtraAccountMetaListInstruction {
        pub accounts: InitializeExtraAccountMetaListInstructionAccountMetas,
        pub data: InitializeExtraAccountMetaListInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeExtraAccountMetaListInstructionAccountMetas {
        pub payer: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub mint: AccountMeta,

        pub sss_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeExtraAccountMetaList instruction
    #[derive(Debug, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionAccounts {
        pub payer: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub mint: Pubkey,

        pub sss_program: Pubkey,
    }

    impl InitializeExtraAccountMetaListInstructionAccounts {
        pub fn new(
            payer: Pubkey,

            extra_account_meta_list: Pubkey,

            mint: Pubkey,

            sss_program: Pubkey,
        ) -> Self {
            Self {
                payer,

                extra_account_meta_list,

                mint,

                sss_program,
            }
        }
    }

    /// Instruction data for InitializeExtraAccountMetaList
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeExtraAccountMetaListInstructionData {}

    impl InitializeExtraAccountMetaListInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeExtraAccountMetaListInstruction
    impl InitializeExtraAccountMetaListInstruction {
        fn discriminator() -> [u8; 8] {
            [92u8, 197u8, 174u8, 197u8, 41u8, 124u8, 19u8, 3u8]
        }

        pub fn data(data: InitializeExtraAccountMetaListInstructionData) -> Self {
            Self {
                accounts: InitializeExtraAccountMetaListInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(
            mut self,
            accounts: InitializeExtraAccountMetaListInstructionAccounts,
        ) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.extra_account_meta_list =
                AccountMeta::new(accounts.extra_account_meta_list, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.sss_program = AccountMeta::new_readonly(accounts.sss_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.sss_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferHook
    // ....................................................................

    /// Main instruction struct for TransferHook
    pub struct TransferHookInstruction {
        pub accounts: TransferHookInstructionAccountMetas,
        pub data: TransferHookInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferHook instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferHookInstructionAccountMetas {
        pub source_token: AccountMeta,

        pub mint: AccountMeta,

        pub destination_token: AccountMeta,

        pub owner: AccountMeta,

        pub extra_account_meta_list: AccountMeta,

        pub sss_program: AccountMeta,

        pub source_owner_blacklist_entry: AccountMeta,

        pub destination_owner_blacklist_entry: AccountMeta,
    }

    /// Account pubkeys for TransferHook instruction
    #[derive(Debug, Clone)]
    pub struct TransferHookInstructionAccounts {
        pub source_token: Pubkey,

        pub mint: Pubkey,

        pub destination_token: Pubkey,

        pub owner: Pubkey,

        pub extra_account_meta_list: Pubkey,

        pub sss_program: Pubkey,

        pub source_owner_blacklist_entry: Pubkey,

        pub destination_owner_blacklist_entry: Pubkey,
    }

    impl TransferHookInstructionAccounts {
        pub fn new(
            source_token: Pubkey,

            mint: Pubkey,

            destination_token: Pubkey,

            owner: Pubkey,

            extra_account_meta_list: Pubkey,

            sss_program: Pubkey,

            source_owner_blacklist_entry: Pubkey,

            destination_owner_blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                source_token,

                mint,

                destination_token,

                owner,

                extra_account_meta_list,

                sss_program,

                source_owner_blacklist_entry,

                destination_owner_blacklist_entry,
            }
        }
    }

    /// Instruction data for TransferHook
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferHookInstructionData {
        pub _amount: u64,
    }

    impl TransferHookInstructionData {
        pub fn new(_amount: u64) -> Self {
            Self { _amount }
        }
    }

    /// Implementation for TransferHookInstruction
    impl TransferHookInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 57u8, 220u8, 152u8, 126u8, 125u8, 97u8, 168u8]
        }

        pub fn data(data: TransferHookInstructionData) -> Self {
            Self {
                accounts: TransferHookInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferHookInstructionAccounts) -> Self {
            self.accounts.source_token = AccountMeta::new_readonly(accounts.source_token, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.destination_token =
                AccountMeta::new_readonly(accounts.destination_token, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, false);

            self.accounts.extra_account_meta_list =
                AccountMeta::new_readonly(accounts.extra_account_meta_list, false);

            self.accounts.sss_program = AccountMeta::new_readonly(accounts.sss_program, false);

            self.accounts.source_owner_blacklist_entry =
                AccountMeta::new_readonly(accounts.source_owner_blacklist_entry, false);

            self.accounts.destination_owner_blacklist_entry =
                AccountMeta::new_readonly(accounts.destination_owner_blacklist_entry, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.source_token.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.destination_token.clone());

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.extra_account_meta_list.clone());

            metas.push(self.accounts.sss_program.clone());

            metas.push(self.accounts.source_owner_blacklist_entry.clone());

            metas.push(self.accounts.destination_owner_blacklist_entry.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: sss
// ----------------------------------------------------------------------------
pub mod sss {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for sss
    pub fn program_id() -> Pubkey {
        pubkey!("7qYYBZqC88Vt61pon3cJnbTpukCsgCETypo13cttMVMG")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AddToBlacklist
    // ....................................................................

    /// Main instruction struct for AddToBlacklist
    pub struct AddToBlacklistInstruction {
        pub accounts: AddToBlacklistInstructionAccountMetas,
        pub data: AddToBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddToBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddToBlacklistInstructionAccountMetas {
        pub blacklister: AccountMeta,

        pub mint: AccountMeta,

        pub config: AccountMeta,

        pub blacklisted_entry: AccountMeta,

        pub system_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for AddToBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct AddToBlacklistInstructionAccounts {
        pub blacklister: Pubkey,

        pub mint: Pubkey,

        pub config: Pubkey,

        pub blacklisted_entry: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl AddToBlacklistInstructionAccounts {
        pub fn new(
            blacklister: Pubkey,

            mint: Pubkey,

            config: Pubkey,

            blacklisted_entry: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                blacklister,

                mint,

                config,

                blacklisted_entry,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for AddToBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddToBlacklistInstructionData {
        pub wallet: Pubkey,

        pub reason: String,
    }

    impl AddToBlacklistInstructionData {
        pub fn new(wallet: Pubkey, reason: String) -> Self {
            Self { wallet, reason }
        }
    }

    /// Implementation for AddToBlacklistInstruction
    impl AddToBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [90u8, 115u8, 98u8, 231u8, 173u8, 119u8, 117u8, 176u8]
        }

        pub fn data(data: AddToBlacklistInstructionData) -> Self {
            Self {
                accounts: AddToBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddToBlacklistInstructionAccounts) -> Self {
            self.accounts.blacklister = AccountMeta::new(accounts.blacklister, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.blacklisted_entry = AccountMeta::new(accounts.blacklisted_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.blacklister.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.blacklisted_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: BurnTokens
    // ....................................................................

    /// Main instruction struct for BurnTokens
    pub struct BurnTokensInstruction {
        pub accounts: BurnTokensInstructionAccountMetas,
        pub data: BurnTokensInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for BurnTokens instruction
    #[derive(Debug, Clone, Default)]
    pub struct BurnTokensInstructionAccountMetas {
        pub burner: AccountMeta,

        pub mint: AccountMeta,

        pub from: AccountMeta,

        pub burner_role: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for BurnTokens instruction
    #[derive(Debug, Clone)]
    pub struct BurnTokensInstructionAccounts {
        pub burner: Pubkey,

        pub mint: Pubkey,

        pub from: Pubkey,

        pub burner_role: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl BurnTokensInstructionAccounts {
        pub fn new(
            burner: Pubkey,

            mint: Pubkey,

            from: Pubkey,

            burner_role: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                burner,

                mint,

                from,

                burner_role,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for BurnTokens
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BurnTokensInstructionData {
        pub amount: u64,
    }

    impl BurnTokensInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for BurnTokensInstruction
    impl BurnTokensInstruction {
        fn discriminator() -> [u8; 8] {
            [76u8, 15u8, 51u8, 254u8, 229u8, 215u8, 121u8, 66u8]
        }

        pub fn data(data: BurnTokensInstructionData) -> Self {
            Self {
                accounts: BurnTokensInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BurnTokensInstructionAccounts) -> Self {
            self.accounts.burner = AccountMeta::new_readonly(accounts.burner, true);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.from = AccountMeta::new(accounts.from, false);

            self.accounts.burner_role = AccountMeta::new_readonly(accounts.burner_role, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.burner.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.from.clone());

            metas.push(self.accounts.burner_role.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FreezeAccount
    // ....................................................................

    /// Main instruction struct for FreezeAccount
    pub struct FreezeAccountInstruction {
        pub accounts: FreezeAccountInstructionAccountMetas,
        pub data: FreezeAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FreezeAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct FreezeAccountInstructionAccountMetas {
        pub master: AccountMeta,

        pub mint: AccountMeta,

        pub ata_to_freeze: AccountMeta,

        pub master_role: AccountMeta,

        pub freeze_authority: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for FreezeAccount instruction
    #[derive(Debug, Clone)]
    pub struct FreezeAccountInstructionAccounts {
        pub master: Pubkey,

        pub mint: Pubkey,

        pub ata_to_freeze: Pubkey,

        pub master_role: Pubkey,

        pub freeze_authority: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl FreezeAccountInstructionAccounts {
        pub fn new(
            master: Pubkey,

            mint: Pubkey,

            ata_to_freeze: Pubkey,

            master_role: Pubkey,

            freeze_authority: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                master,

                mint,

                ata_to_freeze,

                master_role,

                freeze_authority,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for FreezeAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FreezeAccountInstructionData {}

    impl FreezeAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for FreezeAccountInstruction
    impl FreezeAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [253u8, 75u8, 82u8, 133u8, 167u8, 238u8, 43u8, 130u8]
        }

        pub fn data(data: FreezeAccountInstructionData) -> Self {
            Self {
                accounts: FreezeAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FreezeAccountInstructionAccounts) -> Self {
            self.accounts.master = AccountMeta::new_readonly(accounts.master, true);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.ata_to_freeze = AccountMeta::new(accounts.ata_to_freeze, false);

            self.accounts.master_role = AccountMeta::new_readonly(accounts.master_role, false);

            self.accounts.freeze_authority =
                AccountMeta::new_readonly(accounts.freeze_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.master.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.ata_to_freeze.clone());

            metas.push(self.accounts.master_role.clone());

            metas.push(self.accounts.freeze_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub admin: AccountMeta,

        pub mint: AccountMeta,

        pub config: AccountMeta,

        pub mint_authority: AccountMeta,

        pub freeze_authority: AccountMeta,

        pub seizer_authority: AccountMeta,

        pub pause_authority: AccountMeta,

        pub master_role: AccountMeta,

        pub minter_account: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub admin: Pubkey,

        pub mint: Pubkey,

        pub config: Pubkey,

        pub mint_authority: Pubkey,

        pub freeze_authority: Pubkey,

        pub seizer_authority: Pubkey,

        pub pause_authority: Pubkey,

        pub master_role: Pubkey,

        pub minter_account: Pubkey,

        pub token_program: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            mint: Pubkey,

            config: Pubkey,

            mint_authority: Pubkey,

            freeze_authority: Pubkey,

            seizer_authority: Pubkey,

            pause_authority: Pubkey,

            master_role: Pubkey,

            minter_account: Pubkey,

            token_program: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                admin,

                mint,

                config,

                mint_authority,

                freeze_authority,

                seizer_authority,

                pause_authority,

                master_role,

                minter_account,

                token_program,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub standard: Standard,

        pub name: String,

        pub symbol: String,

        pub uri: String,

        pub decimals: u8,

        pub master: Pubkey,

        pub minter: Pubkey,

        pub initial_allowance: u64,

        pub enable_permanent_delegate: Option<bool>,

        pub enable_transfer_hook: Option<bool>,

        pub default_account_frozen: Option<bool>,
    }

    impl InitializeInstructionData {
        pub fn new(
            standard: Standard,

            name: String,

            symbol: String,

            uri: String,

            decimals: u8,

            master: Pubkey,

            minter: Pubkey,

            initial_allowance: u64,

            enable_permanent_delegate: Option<bool>,

            enable_transfer_hook: Option<bool>,

            default_account_frozen: Option<bool>,
        ) -> Self {
            Self {
                standard,

                name,

                symbol,

                uri,

                decimals,

                master,

                minter,

                initial_allowance,

                enable_permanent_delegate,

                enable_transfer_hook,

                default_account_frozen,
            }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.mint = AccountMeta::new(accounts.mint, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.freeze_authority =
                AccountMeta::new_readonly(accounts.freeze_authority, false);

            self.accounts.seizer_authority =
                AccountMeta::new_readonly(accounts.seizer_authority, false);

            self.accounts.pause_authority =
                AccountMeta::new_readonly(accounts.pause_authority, false);

            self.accounts.master_role = AccountMeta::new(accounts.master_role, false);

            self.accounts.minter_account = AccountMeta::new(accounts.minter_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.freeze_authority.clone());

            metas.push(self.accounts.seizer_authority.clone());

            metas.push(self.accounts.pause_authority.clone());

            metas.push(self.accounts.master_role.clone());

            metas.push(self.accounts.minter_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: MintTokens
    // ....................................................................

    /// Main instruction struct for MintTokens
    pub struct MintTokensInstruction {
        pub accounts: MintTokensInstructionAccountMetas,
        pub data: MintTokensInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for MintTokens instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintTokensInstructionAccountMetas {
        pub minter: AccountMeta,

        pub mint: AccountMeta,

        pub to: AccountMeta,

        pub minter_account: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for MintTokens instruction
    #[derive(Debug, Clone)]
    pub struct MintTokensInstructionAccounts {
        pub minter: Pubkey,

        pub mint: Pubkey,

        pub to: Pubkey,

        pub minter_account: Pubkey,

        pub mint_authority: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl MintTokensInstructionAccounts {
        pub fn new(
            minter: Pubkey,

            mint: Pubkey,

            to: Pubkey,

            minter_account: Pubkey,

            mint_authority: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                minter,

                mint,

                to,

                minter_account,

                mint_authority,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for MintTokens
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintTokensInstructionData {
        pub amount: u64,
    }

    impl MintTokensInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintTokensInstruction
    impl MintTokensInstruction {
        fn discriminator() -> [u8; 8] {
            [59u8, 132u8, 24u8, 246u8, 122u8, 39u8, 8u8, 243u8]
        }

        pub fn data(data: MintTokensInstructionData) -> Self {
            Self {
                accounts: MintTokensInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintTokensInstructionAccounts) -> Self {
            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, true);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.to = AccountMeta::new(accounts.to, false);

            self.accounts.minter_account = AccountMeta::new(accounts.minter_account, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.to.clone());

            metas.push(self.accounts.minter_account.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pause
    // ....................................................................

    /// Main instruction struct for Pause
    pub struct PauseInstruction {
        pub accounts: PauseInstructionAccountMetas,
        pub data: PauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pause instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseInstructionAccountMetas {
        pub pauser: AccountMeta,

        pub mint: AccountMeta,

        pub pauser_role: AccountMeta,

        pub pause_authority: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for Pause instruction
    #[derive(Debug, Clone)]
    pub struct PauseInstructionAccounts {
        pub pauser: Pubkey,

        pub mint: Pubkey,

        pub pauser_role: Pubkey,

        pub pause_authority: Pubkey,

        pub token_program: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl PauseInstructionAccounts {
        pub fn new(
            pauser: Pubkey,

            mint: Pubkey,

            pauser_role: Pubkey,

            pause_authority: Pubkey,

            token_program: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                pauser,

                mint,

                pauser_role,

                pause_authority,

                token_program,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for Pause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseInstructionData {}

    impl PauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseInstruction
    impl PauseInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 22u8, 221u8, 251u8, 74u8, 121u8, 193u8, 47u8]
        }

        pub fn data(data: PauseInstructionData) -> Self {
            Self {
                accounts: PauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseInstructionAccounts) -> Self {
            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.pauser_role = AccountMeta::new_readonly(accounts.pauser_role, false);

            self.accounts.pause_authority =
                AccountMeta::new_readonly(accounts.pause_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pauser.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.pauser_role.clone());

            metas.push(self.accounts.pause_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveFromBlacklist
    // ....................................................................

    /// Main instruction struct for RemoveFromBlacklist
    pub struct RemoveFromBlacklistInstruction {
        pub accounts: RemoveFromBlacklistInstructionAccountMetas,
        pub data: RemoveFromBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveFromBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveFromBlacklistInstructionAccountMetas {
        pub blacklister: AccountMeta,

        pub mint: AccountMeta,

        pub config: AccountMeta,

        pub blacklisted_entry: AccountMeta,

        pub system_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for RemoveFromBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct RemoveFromBlacklistInstructionAccounts {
        pub blacklister: Pubkey,

        pub mint: Pubkey,

        pub config: Pubkey,

        pub blacklisted_entry: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl RemoveFromBlacklistInstructionAccounts {
        pub fn new(
            blacklister: Pubkey,

            mint: Pubkey,

            config: Pubkey,

            blacklisted_entry: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                blacklister,

                mint,

                config,

                blacklisted_entry,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for RemoveFromBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveFromBlacklistInstructionData {
        pub wallet: Pubkey,
    }

    impl RemoveFromBlacklistInstructionData {
        pub fn new(wallet: Pubkey) -> Self {
            Self { wallet }
        }
    }

    /// Implementation for RemoveFromBlacklistInstruction
    impl RemoveFromBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [47u8, 105u8, 20u8, 10u8, 165u8, 168u8, 203u8, 219u8]
        }

        pub fn data(data: RemoveFromBlacklistInstructionData) -> Self {
            Self {
                accounts: RemoveFromBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveFromBlacklistInstructionAccounts) -> Self {
            self.accounts.blacklister = AccountMeta::new(accounts.blacklister, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.blacklisted_entry = AccountMeta::new(accounts.blacklisted_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.blacklister.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.blacklisted_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Seize
    // ....................................................................

    /// Main instruction struct for Seize
    pub struct SeizeInstruction {
        pub accounts: SeizeInstructionAccountMetas,
        pub data: SeizeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Seize instruction
    #[derive(Debug, Clone, Default)]
    pub struct SeizeInstructionAccountMetas {
        pub seizer: AccountMeta,

        pub seizer_authority: AccountMeta,

        pub seizer_role: AccountMeta,

        pub stablecoin_config: AccountMeta,

        pub from: AccountMeta,

        pub to: AccountMeta,

        pub mint: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for Seize instruction
    #[derive(Debug, Clone)]
    pub struct SeizeInstructionAccounts {
        pub seizer: Pubkey,

        pub seizer_authority: Pubkey,

        pub seizer_role: Pubkey,

        pub stablecoin_config: Pubkey,

        pub from: Pubkey,

        pub to: Pubkey,

        pub mint: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl SeizeInstructionAccounts {
        pub fn new(
            seizer: Pubkey,

            seizer_authority: Pubkey,

            seizer_role: Pubkey,

            stablecoin_config: Pubkey,

            from: Pubkey,

            to: Pubkey,

            mint: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                seizer,

                seizer_authority,

                seizer_role,

                stablecoin_config,

                from,

                to,

                mint,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for Seize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SeizeInstructionData {
        pub amount: u64,
    }

    impl SeizeInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for SeizeInstruction
    impl SeizeInstruction {
        fn discriminator() -> [u8; 8] {
            [129u8, 159u8, 143u8, 31u8, 161u8, 224u8, 241u8, 84u8]
        }

        pub fn data(data: SeizeInstructionData) -> Self {
            Self {
                accounts: SeizeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SeizeInstructionAccounts) -> Self {
            self.accounts.seizer = AccountMeta::new(accounts.seizer, true);

            self.accounts.seizer_authority =
                AccountMeta::new_readonly(accounts.seizer_authority, false);

            self.accounts.seizer_role = AccountMeta::new_readonly(accounts.seizer_role, false);

            self.accounts.stablecoin_config =
                AccountMeta::new_readonly(accounts.stablecoin_config, false);

            self.accounts.from = AccountMeta::new(accounts.from, false);

            self.accounts.to = AccountMeta::new(accounts.to, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.seizer.clone());

            metas.push(self.accounts.seizer_authority.clone());

            metas.push(self.accounts.seizer_role.clone());

            metas.push(self.accounts.stablecoin_config.clone());

            metas.push(self.accounts.from.clone());

            metas.push(self.accounts.to.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ThawAccount
    // ....................................................................

    /// Main instruction struct for ThawAccount
    pub struct ThawAccountInstruction {
        pub accounts: ThawAccountInstructionAccountMetas,
        pub data: ThawAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ThawAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct ThawAccountInstructionAccountMetas {
        pub master: AccountMeta,

        pub mint: AccountMeta,

        pub ata_to_thaw: AccountMeta,

        pub master_role: AccountMeta,

        pub freeze_authority: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for ThawAccount instruction
    #[derive(Debug, Clone)]
    pub struct ThawAccountInstructionAccounts {
        pub master: Pubkey,

        pub mint: Pubkey,

        pub ata_to_thaw: Pubkey,

        pub master_role: Pubkey,

        pub freeze_authority: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl ThawAccountInstructionAccounts {
        pub fn new(
            master: Pubkey,

            mint: Pubkey,

            ata_to_thaw: Pubkey,

            master_role: Pubkey,

            freeze_authority: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                master,

                mint,

                ata_to_thaw,

                master_role,

                freeze_authority,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for ThawAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ThawAccountInstructionData {}

    impl ThawAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ThawAccountInstruction
    impl ThawAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [115u8, 152u8, 79u8, 213u8, 213u8, 169u8, 184u8, 35u8]
        }

        pub fn data(data: ThawAccountInstructionData) -> Self {
            Self {
                accounts: ThawAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ThawAccountInstructionAccounts) -> Self {
            self.accounts.master = AccountMeta::new_readonly(accounts.master, true);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.ata_to_thaw = AccountMeta::new(accounts.ata_to_thaw, false);

            self.accounts.master_role = AccountMeta::new_readonly(accounts.master_role, false);

            self.accounts.freeze_authority =
                AccountMeta::new_readonly(accounts.freeze_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.master.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.ata_to_thaw.clone());

            metas.push(self.accounts.master_role.clone());

            metas.push(self.accounts.freeze_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferAuthority
    // ....................................................................

    /// Main instruction struct for TransferAuthority
    pub struct TransferAuthorityInstruction {
        pub accounts: TransferAuthorityInstructionAccountMetas,
        pub data: TransferAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferAuthorityInstructionAccountMetas {
        pub master: AccountMeta,

        pub mint: AccountMeta,

        pub master_role: AccountMeta,

        pub new_master_role: AccountMeta,

        pub system_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for TransferAuthority instruction
    #[derive(Debug, Clone)]
    pub struct TransferAuthorityInstructionAccounts {
        pub master: Pubkey,

        pub mint: Pubkey,

        pub master_role: Pubkey,

        pub new_master_role: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl TransferAuthorityInstructionAccounts {
        pub fn new(
            master: Pubkey,

            mint: Pubkey,

            master_role: Pubkey,

            new_master_role: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                master,

                mint,

                master_role,

                new_master_role,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for TransferAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferAuthorityInstructionData {
        pub new_master: Pubkey,
    }

    impl TransferAuthorityInstructionData {
        pub fn new(new_master: Pubkey) -> Self {
            Self { new_master }
        }
    }

    /// Implementation for TransferAuthorityInstruction
    impl TransferAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [48u8, 169u8, 76u8, 72u8, 229u8, 180u8, 55u8, 161u8]
        }

        pub fn data(data: TransferAuthorityInstructionData) -> Self {
            Self {
                accounts: TransferAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferAuthorityInstructionAccounts) -> Self {
            self.accounts.master = AccountMeta::new(accounts.master, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.master_role = AccountMeta::new(accounts.master_role, false);

            self.accounts.new_master_role = AccountMeta::new(accounts.new_master_role, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.master.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.master_role.clone());

            metas.push(self.accounts.new_master_role.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Unpause
    // ....................................................................

    /// Main instruction struct for Unpause
    pub struct UnpauseInstruction {
        pub accounts: UnpauseInstructionAccountMetas,
        pub data: UnpauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Unpause instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpauseInstructionAccountMetas {
        pub pauser: AccountMeta,

        pub mint: AccountMeta,

        pub pauser_role: AccountMeta,

        pub pause_authority: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for Unpause instruction
    #[derive(Debug, Clone)]
    pub struct UnpauseInstructionAccounts {
        pub pauser: Pubkey,

        pub mint: Pubkey,

        pub pauser_role: Pubkey,

        pub pause_authority: Pubkey,

        pub token_program: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl UnpauseInstructionAccounts {
        pub fn new(
            pauser: Pubkey,

            mint: Pubkey,

            pauser_role: Pubkey,

            pause_authority: Pubkey,

            token_program: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                pauser,

                mint,

                pauser_role,

                pause_authority,

                token_program,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for Unpause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpauseInstructionData {}

    impl UnpauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpauseInstruction
    impl UnpauseInstruction {
        fn discriminator() -> [u8; 8] {
            [169u8, 144u8, 4u8, 38u8, 10u8, 141u8, 188u8, 255u8]
        }

        pub fn data(data: UnpauseInstructionData) -> Self {
            Self {
                accounts: UnpauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpauseInstructionAccounts) -> Self {
            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.pauser_role = AccountMeta::new_readonly(accounts.pauser_role, false);

            self.accounts.pause_authority =
                AccountMeta::new_readonly(accounts.pause_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pauser.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.pauser_role.clone());

            metas.push(self.accounts.pause_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateMinter
    // ....................................................................

    /// Main instruction struct for UpdateMinter
    pub struct UpdateMinterInstruction {
        pub accounts: UpdateMinterInstructionAccountMetas,
        pub data: UpdateMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateMinterInstructionAccountMetas {
        pub master: AccountMeta,

        pub mint: AccountMeta,

        pub master_role: AccountMeta,

        pub update_minter: AccountMeta,

        pub system_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for UpdateMinter instruction
    #[derive(Debug, Clone)]
    pub struct UpdateMinterInstructionAccounts {
        pub master: Pubkey,

        pub mint: Pubkey,

        pub master_role: Pubkey,

        pub update_minter: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl UpdateMinterInstructionAccounts {
        pub fn new(
            master: Pubkey,

            mint: Pubkey,

            master_role: Pubkey,

            update_minter: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                master,

                mint,

                master_role,

                update_minter,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for UpdateMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateMinterInstructionData {
        pub operation: String,

        pub minter: Pubkey,

        pub allowance: u64,
    }

    impl UpdateMinterInstructionData {
        pub fn new(operation: String, minter: Pubkey, allowance: u64) -> Self {
            Self {
                operation,

                minter,

                allowance,
            }
        }
    }

    /// Implementation for UpdateMinterInstruction
    impl UpdateMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [164u8, 129u8, 164u8, 88u8, 75u8, 29u8, 91u8, 38u8]
        }

        pub fn data(data: UpdateMinterInstructionData) -> Self {
            Self {
                accounts: UpdateMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateMinterInstructionAccounts) -> Self {
            self.accounts.master = AccountMeta::new(accounts.master, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.master_role = AccountMeta::new_readonly(accounts.master_role, false);

            self.accounts.update_minter = AccountMeta::new(accounts.update_minter, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.master.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.master_role.clone());

            metas.push(self.accounts.update_minter.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateRoles
    // ....................................................................

    /// Main instruction struct for UpdateRoles
    pub struct UpdateRolesInstruction {
        pub accounts: UpdateRolesInstructionAccountMetas,
        pub data: UpdateRolesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateRoles instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateRolesInstructionAccountMetas {
        pub master: AccountMeta,

        pub mint: AccountMeta,

        pub master_role: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for UpdateRoles instruction
    #[derive(Debug, Clone)]
    pub struct UpdateRolesInstructionAccounts {
        pub master: Pubkey,

        pub mint: Pubkey,

        pub master_role: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl UpdateRolesInstructionAccounts {
        pub fn new(
            master: Pubkey,

            mint: Pubkey,

            master_role: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                master,

                mint,

                master_role,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for UpdateRoles
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateRolesInstructionData {
        pub roles: Vec<UpdateRole>,
    }

    impl UpdateRolesInstructionData {
        pub fn new(roles: Vec<UpdateRole>) -> Self {
            Self { roles }
        }
    }

    /// Implementation for UpdateRolesInstruction
    impl UpdateRolesInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 152u8, 205u8, 233u8, 177u8, 123u8, 219u8, 125u8]
        }

        pub fn data(data: UpdateRolesInstructionData) -> Self {
            Self {
                accounts: UpdateRolesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateRolesInstructionAccounts) -> Self {
            self.accounts.master = AccountMeta::new(accounts.master, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.master_role = AccountMeta::new_readonly(accounts.master_role, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.master.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.master_role.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: AddToBlacklistEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AddToBlacklistEvent {
    pub blacklisted: Pubkey,

    pub mint: Pubkey,

    pub reason: String,
}

impl AddToBlacklistEvent {
    pub fn new(blacklisted: Pubkey, mint: Pubkey, reason: String) -> Self {
        Self {
            blacklisted,

            mint,

            reason,
        }
    }
}

/// Custom struct: BlacklistedEntry
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistedEntry {
    pub bump: u8,

    pub is_blacklisted: bool,

    pub reason: String,
}

impl BlacklistedEntry {
    pub fn new(bump: u8, is_blacklisted: bool, reason: String) -> Self {
        Self {
            bump,

            is_blacklisted,

            reason,
        }
    }
}

/// Custom struct: BurnTokensEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BurnTokensEvent {
    pub burner: Pubkey,

    pub mint: Pubkey,

    pub from: Pubkey,

    pub amount: u64,
}

impl BurnTokensEvent {
    pub fn new(burner: Pubkey, mint: Pubkey, from: Pubkey, amount: u64) -> Self {
        Self {
            burner,

            mint,

            from,

            amount,
        }
    }
}

/// Custom struct: FreezeAccountEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct FreezeAccountEvent {
    pub ata_to_freeze: Pubkey,

    pub mint: Pubkey,
}

impl FreezeAccountEvent {
    pub fn new(ata_to_freeze: Pubkey, mint: Pubkey) -> Self {
        Self {
            ata_to_freeze,

            mint,
        }
    }
}

/// Custom struct: InitializeEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializeEvent {
    pub mint: Pubkey,

    pub standard: String,

    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,
}

impl InitializeEvent {
    pub fn new(
        mint: Pubkey,

        standard: String,

        name: String,

        symbol: String,

        uri: String,

        decimals: u8,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,
    ) -> Self {
        Self {
            mint,

            standard,

            name,

            symbol,

            uri,

            decimals,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,
        }
    }
}

/// Custom struct: MintTokensEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MintTokensEvent {
    pub minter: Pubkey,

    pub to: Pubkey,

    pub mint: Pubkey,

    pub amount: u64,
}

impl MintTokensEvent {
    pub fn new(minter: Pubkey, to: Pubkey, mint: Pubkey, amount: u64) -> Self {
        Self {
            minter,

            to,

            mint,

            amount,
        }
    }
}

/// Custom struct: MinterAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterAccount {
    pub bump: u8,

    pub allowance: u64,

    pub minted: u64,

    pub mint: Pubkey,
}

impl MinterAccount {
    pub fn new(bump: u8, allowance: u64, minted: u64, mint: Pubkey) -> Self {
        Self {
            bump,

            allowance,

            minted,

            mint,
        }
    }
}

/// Custom struct: PauseEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PauseEvent {
    pub pauser: Pubkey,

    pub mint: Pubkey,
}

impl PauseEvent {
    pub fn new(pauser: Pubkey, mint: Pubkey) -> Self {
        Self { pauser, mint }
    }
}

/// Custom struct: RemoveFromBlacklistEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RemoveFromBlacklistEvent {
    pub wallet: Pubkey,

    pub mint: Pubkey,
}

impl RemoveFromBlacklistEvent {
    pub fn new(wallet: Pubkey, mint: Pubkey) -> Self {
        Self { wallet, mint }
    }
}

/// Custom struct: RoleAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleAccount {
    pub bump: u8,
}

impl RoleAccount {
    pub fn new(bump: u8) -> Self {
        Self { bump }
    }
}

/// Custom struct: SeizeEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SeizeEvent {
    pub seizer: Pubkey,

    pub from: Pubkey,

    pub to: Pubkey,

    pub mint: Pubkey,
}

impl SeizeEvent {
    pub fn new(seizer: Pubkey, from: Pubkey, to: Pubkey, mint: Pubkey) -> Self {
        Self {
            seizer,

            from,

            to,

            mint,
        }
    }
}

/// Custom struct: StablecoinConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinConfig {
    pub bump: u8,

    pub standard: Standard,

    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,
}

impl StablecoinConfig {
    pub fn new(
        bump: u8,

        standard: Standard,

        name: String,

        symbol: String,

        uri: String,

        decimals: u8,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,
    ) -> Self {
        Self {
            bump,

            standard,

            name,

            symbol,

            uri,

            decimals,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,
        }
    }
}

/// Custom enum: Standard
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq, Eq)]
pub enum Standard {
    SSS1,

    SSS2,
}

/// Custom struct: ThawAccountEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ThawAccountEvent {
    pub master: Pubkey,

    pub ata_to_thaw: Pubkey,

    pub mint: Pubkey,
}

impl ThawAccountEvent {
    pub fn new(master: Pubkey, ata_to_thaw: Pubkey, mint: Pubkey) -> Self {
        Self {
            master,

            ata_to_thaw,

            mint,
        }
    }
}

/// Custom struct: TransferAuthorityEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TransferAuthorityEvent {
    pub master: Pubkey,

    pub new_master: Pubkey,

    pub mint: Pubkey,
}

impl TransferAuthorityEvent {
    pub fn new(master: Pubkey, new_master: Pubkey, mint: Pubkey) -> Self {
        Self {
            master,

            new_master,

            mint,
        }
    }
}

/// Custom struct: UnpauseEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UnpauseEvent {
    pub pauser: Pubkey,

    pub mint: Pubkey,
}

impl UnpauseEvent {
    pub fn new(pauser: Pubkey, mint: Pubkey) -> Self {
        Self { pauser, mint }
    }
}

/// Custom struct: UpdateMinterEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UpdateMinterEvent {
    pub operation: String,

    pub mint: Pubkey,

    pub minter: Pubkey,

    pub allowance: u64,
}

impl UpdateMinterEvent {
    pub fn new(operation: String, mint: Pubkey, minter: Pubkey, allowance: u64) -> Self {
        Self {
            operation,

            mint,

            minter,

            allowance,
        }
    }
}

/// Custom struct: UpdateRole
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UpdateRole {
    pub role: String,

    pub old_key: Option<Pubkey>,

    pub new_key: Pubkey,

    pub allowance: u64,
}

impl UpdateRole {
    pub fn new(role: String, old_key: Option<Pubkey>, new_key: Pubkey, allowance: u64) -> Self {
        Self {
            role,

            old_key,

            new_key,

            allowance,
        }
    }
}

/// Custom struct: UpdateRolesEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UpdateRolesEvent {
    pub role: String,

    pub mint: Pubkey,

    pub master: Pubkey,
}

impl UpdateRolesEvent {
    pub fn new(role: String, mint: Pubkey, master: Pubkey) -> Self {
        Self { role, mint, master }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
