[features]
seeds = false
skip-lint = false

[programs.localnet]
sss = "88tCFqhg7EFqGcYoV2Gb19g781KT6LbbH3sprGt5p5XC"
transfer_hook = "4pf4aBSu8VS4qVsrwC9T1GvsCJatiD3D6fw2qFPYgZjG"
oracle_module = "BqXApTus5EWmrMAgDhLg8rmbq6fnW7XV4CbaCmUBMSTQ"

[programs.devnet]
sss = "88tCFqhg7EFqGcYoV2Gb19g781KT6LbbH3sprGt5p5XC"
transfer_hook = "4pf4aBSu8VS4qVsrwC9T1GvsCJatiD3D6fw2qFPYgZjG"
# oracle_module = "BqXApTus5EWmrMAgDhLg8rmbq6fnW7XV4CbaCmUBMSTQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.30.0"

