[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sss_token = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
transfer_hook = "HmbTLCmaGtYhSJaoxkmcJA2MkRYEbn7gxjoYDMgbGnHb"
oracle_module = "J4ywvRqWbRSuijhFkvSfMbjXZvzR2eJYyGBJASarBPJc"

[programs.devnet]
sss_token = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
transfer_hook = "HmbTLCmaGtYhSJaoxkmcJA2MkRYEbn7gxjoYDMgbGnHb"
oracle_module = "J4ywvRqWbRSuijhFkvSfMbjXZvzR2eJYyGBJASarBPJc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "http://127.0.0.1:18899"
rpc_port = 18899
faucet_port = 18901

[scripts]
test = "node_modules/.bin/mocha --require tsx -t 1000000 'tests/**/*.test.ts'"
