[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sss_core = "451UiDzutoMvqZkEj94PSNQTZELV4JqWRdiSoiJB9bxp"
transfer_hook = "5cs7VzZny1XMj4TAJy2xVqo2tCHM8Vwe9bNbL6uRmbxk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/**/*.ts"
