import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import { Keypair, PublicKey, SystemProgram, SYSVAR_RENT_PUBKEY } from "@solana/web3.js";
import {
  TOKEN_2022_PROGRAM_ID,
  getAssociatedTokenAddressSync,
  createAssociatedTokenAccountInstruction,
  getAccount,
} from "@solana/spl-token";
import { assert, expect } from "chai";

// Import SDK helpers for PDA derivation
import {
  deriveConfigPda,
  deriveRolesPda,
} from "@stbr/sss-token";

// ── Test Helpers ──────────────────────────────────────────────────────

/**
 * Generates a new funded keypair for testing.
 */
async function fundedKeypair(
  provider: anchor.AnchorProvider,
  lamports = 5 * anchor.web3.LAMPORTS_PER_SOL
): Promise<Keypair> {
  const kp = Keypair.generate();
  const sig = await provider.connection.requestAirdrop(kp.publicKey, lamports);
  await provider.connection.confirmTransaction(sig, "confirmed");
  return kp;
}

/**
 * Creates an ATA for a wallet if it doesn't exist.
 */
async function ensureAta(
  provider: anchor.AnchorProvider,
  mint: PublicKey,
  owner: PublicKey,
  payer: Keypair
): Promise<PublicKey> {
  const ata = getAssociatedTokenAddressSync(mint, owner, false, TOKEN_2022_PROGRAM_ID);
  const info = await provider.connection.getAccountInfo(ata);
  if (!info) {
    const ix = createAssociatedTokenAccountInstruction(
      payer.publicKey,
      ata,
      owner,
      mint,
      TOKEN_2022_PROGRAM_ID
    );
    const tx = new anchor.web3.Transaction().add(ix);
    await anchor.web3.sendAndConfirmTransaction(provider.connection, tx, [payer]);
  }
  return ata;
}

// ── SSS-1 Test Suite ──────────────────────────────────────────────────

describe("sss-1: Minimal Stablecoin", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // Load the Anchor program from workspace (IDL generated by `anchor build`)
  const program = anchor.workspace.SssToken as Program;

  // Shared state across tests
  let authority: Keypair;
  let mintKeypair: Keypair;
  let configPda: PublicKey;
  let configBump: number;
  let rolesPda: PublicKey;
  let rolesBump: number;
  let minterKeypair: Keypair;
  let userKeypair: Keypair;

  // ── Setup ─────────────────────────────────────────────────────────

  before(async () => {
    authority = provider.wallet.payer;
    mintKeypair = Keypair.generate();
    minterKeypair = await fundedKeypair(provider);
    userKeypair = await fundedKeypair(provider);

    // Derive PDAs using SDK helpers
    [configPda, configBump] = deriveConfigPda(mintKeypair.publicKey, program.programId);
    [rolesPda, rolesBump] = deriveRolesPda(configPda, program.programId);
  });

  // ── Test 1: Initialize ────────────────────────────────────────────

  it("initializes an SSS-1 stablecoin", async () => {
    const tx = await program.methods
      .initialize({
        name: "Test USD",
        symbol: "TUSD",
        uri: "https://example.com/metadata.json",
        decimals: 6,
        enablePermanentDelegate: false,
        enableTransferHook: false,
        enableConfidentialTransfers: false,
        defaultAccountFrozen: false,
        pauser: authority.publicKey,
        blacklister: null,
        seizer: null,
      })
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        roleManager: rolesPda,
        mint: mintKeypair.publicKey,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([mintKeypair])
      .rpc();


    // Verify config account
    const config = await program.account.stablecoinConfig.fetch(configPda);
    assert.equal(config.name, "Test USD");
    assert.equal(config.symbol, "TUSD");
    assert.equal(config.decimals, 6);
    assert.isFalse(config.isPaused);
    assert.isFalse(config.enablePermanentDelegate);
    assert.isFalse(config.enableTransferHook);
    assert.equal(config.totalMinted.toNumber(), 0);
    assert.equal(config.totalBurned.toNumber(), 0);
    assert.ok(config.authority.equals(authority.publicKey));
    assert.ok(config.mint.equals(mintKeypair.publicKey));

    // Verify role manager
    const roles = await program.account.roleManager.fetch(rolesPda);
    assert.ok(roles.masterAuthority.equals(authority.publicKey));
    assert.ok(roles.pauser.equals(authority.publicKey));
    assert.equal(roles.minters.length, 0);
    // Authority is automatically added as burner during init
    assert.equal(roles.burners.length, 1);
    assert.ok(roles.burners[0].equals(authority.publicKey));
  });

  // ── Test 2: Add Minter ────────────────────────────────────────────

  it("adds a minter with quota", async () => {
    const quota = new BN(1_000_000_000); // 1000 tokens at 6 decimals

    await program.methods
      .updateMinter(minterKeypair.publicKey, quota)
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        roleManager: rolesPda,
      })
      .rpc();

    const roles = await program.account.roleManager.fetch(rolesPda);
    assert.equal(roles.minters.length, 1);
    assert.ok(roles.minters[0].address.equals(minterKeypair.publicKey));
    assert.equal(roles.minters[0].quota.toNumber(), 1_000_000_000);
    assert.equal(roles.minters[0].minted.toNumber(), 0);
  });

  // ── Test 3: Mint Tokens ───────────────────────────────────────────

  it("mints tokens with valid minter", async () => {
    const amount = new BN(100_000_000); // 100 tokens

    // Create ATA for recipient
    const recipientAta = await ensureAta(
      provider, mintKeypair.publicKey, userKeypair.publicKey, authority
    );

    await program.methods
      .mintTokens(amount)
      .accounts({
        minter: minterKeypair.publicKey,
        config: configPda,
        roleManager: rolesPda,
        mint: mintKeypair.publicKey,
        recipientTokenAccount: recipientAta,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
      })
      .signers([minterKeypair])
      .rpc();

    // Check token balance
    const tokenAccount = await getAccount(
      provider.connection, recipientAta, "confirmed", TOKEN_2022_PROGRAM_ID
    );
    assert.equal(Number(tokenAccount.amount), 100_000_000);

    // Check config total_minted
    const config = await program.account.stablecoinConfig.fetch(configPda);
    assert.equal(config.totalMinted.toNumber(), 100_000_000);

    // Check minter's quota was decremented
    const roles = await program.account.roleManager.fetch(rolesPda);
    assert.equal(roles.minters[0].minted.toNumber(), 100_000_000);
  });

  // ── Test 4: Reject Unauthorized Minter ────────────────────────────

  it("rejects mint from unauthorized minter", async () => {
    const attacker = await fundedKeypair(provider);
    const attackerAta = await ensureAta(
      provider, mintKeypair.publicKey, attacker.publicKey, authority
    );

    try {
      await program.methods
        .mintTokens(new BN(1))
        .accounts({
          minter: attacker.publicKey,
          config: configPda,
          roleManager: rolesPda,
          mint: mintKeypair.publicKey,
          recipientTokenAccount: attackerAta,
          tokenProgram: TOKEN_2022_PROGRAM_ID,
        })
        .signers([attacker])
        .rpc();
      assert.fail("Should have thrown");
    } catch (err: any) {
      // Should fail with UnauthorizedMinter
      assert.include(err.toString(), "Unauthorized");
    }
  });

  // ── Test 5: Mint Quota Enforcement ────────────────────────────────

  it("rejects mint exceeding quota", async () => {
    // Minter has 1B quota, already minted 100M. Try to mint the remaining 901M
    const amount = new BN(901_000_000); // 1M over remaining quota
    const recipientAta = getAssociatedTokenAddressSync(
      mintKeypair.publicKey, userKeypair.publicKey, false, TOKEN_2022_PROGRAM_ID
    );

    try {
      await program.methods
        .mintTokens(amount)
        .accounts({
          minter: minterKeypair.publicKey,
          config: configPda,
          roleManager: rolesPda,
          mint: mintKeypair.publicKey,
          recipientTokenAccount: recipientAta,
          tokenProgram: TOKEN_2022_PROGRAM_ID,
        })
        .signers([minterKeypair])
        .rpc();
      assert.fail("Should have thrown");
    } catch (err: any) {
      assert.include(err.toString(), "quota");
    }
  });

  // ── Test 6: Burn Tokens ───────────────────────────────────────────

  it("burns tokens", async () => {
    // User needs to be a burner to burn. Add user as burner first.
    await program.methods
      .updateRoles({
        newPauser: null,
        newBlacklister: null,
        newSeizer: null,
        addBurner: userKeypair.publicKey,
        removeBurner: null,
      })
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        roleManager: rolesPda,
      })
      .rpc();

    const burnAmount = new BN(10_000_000); // 10 tokens
    const burnerAta = getAssociatedTokenAddressSync(
      mintKeypair.publicKey, userKeypair.publicKey, false, TOKEN_2022_PROGRAM_ID
    );

    await program.methods
      .burnTokens(burnAmount)
      .accounts({
        burner: userKeypair.publicKey,
        config: configPda,
        roleManager: rolesPda,
        mint: mintKeypair.publicKey,
        burnerTokenAccount: burnerAta,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
      })
      .signers([userKeypair])
      .rpc();

    // Check balance reduced
    const tokenAccount = await getAccount(
      provider.connection, burnerAta, "confirmed", TOKEN_2022_PROGRAM_ID
    );
    assert.equal(Number(tokenAccount.amount), 90_000_000); // 100M - 10M

    // Check config total_burned
    const config = await program.account.stablecoinConfig.fetch(configPda);
    assert.equal(config.totalBurned.toNumber(), 10_000_000);

  });

  // ── Test 7: Freeze and Thaw ───────────────────────────────────────

  it("freezes and thaws a token account", async () => {
    const tokenAccount = getAssociatedTokenAddressSync(
      mintKeypair.publicKey, userKeypair.publicKey, false, TOKEN_2022_PROGRAM_ID
    );

    // Freeze
    await program.methods
      .freezeAccount()
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        roleManager: rolesPda,
        mint: mintKeypair.publicKey,
        tokenAccount,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
      })
      .rpc({ commitment: "confirmed" });

    let account = await getAccount(
      provider.connection, tokenAccount, "confirmed", TOKEN_2022_PROGRAM_ID
    );
    assert.isTrue(account.isFrozen, "Account should be frozen after freeze_account");

    // Thaw
    await program.methods
      .thawAccount()
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        roleManager: rolesPda,
        mint: mintKeypair.publicKey,
        tokenAccount,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
      })
      .rpc({ commitment: "confirmed" });

    account = await getAccount(
      provider.connection, tokenAccount, "confirmed", TOKEN_2022_PROGRAM_ID
    );
    assert.isFalse(account.isFrozen);
  });

  // ── Test 8: Pause and Unpause ─────────────────────────────────────

  it("pauses and unpauses operations", async () => {
    // Pause
    await program.methods
      .pause()
      .accounts({
        pauser: authority.publicKey,
        config: configPda,
        roleManager: rolesPda,
      })
      .rpc();

    let config = await program.account.stablecoinConfig.fetch(configPda);
    assert.isTrue(config.isPaused);

    // Attempt mint while paused — should fail
    const recipientAta = getAssociatedTokenAddressSync(
      mintKeypair.publicKey, userKeypair.publicKey, false, TOKEN_2022_PROGRAM_ID
    );
    try {
      await program.methods
        .mintTokens(new BN(1))
        .accounts({
          minter: minterKeypair.publicKey,
          config: configPda,
          roleManager: rolesPda,
          mint: mintKeypair.publicKey,
          recipientTokenAccount: recipientAta,
          tokenProgram: TOKEN_2022_PROGRAM_ID,
        })
        .signers([minterKeypair])
        .rpc();
      assert.fail("Should have thrown");
    } catch (err: any) {
      assert.include(err.toString(), "paused");
    }

    // Unpause
    await program.methods
      .unpause()
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        roleManager: rolesPda,
      })
      .rpc();

    config = await program.account.stablecoinConfig.fetch(configPda);
    assert.isFalse(config.isPaused);
  });

  // ── Test 9: Remove Minter ─────────────────────────────────────────

  it("removes a minter", async () => {
    await program.methods
      .removeMinter(minterKeypair.publicKey)
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        roleManager: rolesPda,
      })
      .rpc();

    const roles = await program.account.roleManager.fetch(rolesPda);
    assert.equal(roles.minters.length, 0);
  });

  // ── Test 10: Transfer Authority ───────────────────────────────────

  it("transfers authority", async () => {
    const newAuthority = await fundedKeypair(provider);

    await program.methods
      .transferAuthority(newAuthority.publicKey)
      .accounts({
        authority: authority.publicKey,
        config: configPda,
        roleManager: rolesPda,
      })
      .rpc();

    const config = await program.account.stablecoinConfig.fetch(configPda);
    assert.ok(config.authority.equals(newAuthority.publicKey));

    const roles = await program.account.roleManager.fetch(rolesPda);
    assert.ok(roles.masterAuthority.equals(newAuthority.publicKey));

    // Transfer back for subsequent tests
    await program.methods
      .transferAuthority(authority.publicKey)
      .accounts({
        authority: newAuthority.publicKey,
        config: configPda,
        roleManager: rolesPda,
      })
      .signers([newAuthority])
      .rpc();

  });
});
