import {
  Connection,
  PublicKey,
  Keypair,
  TransactionInstruction,
  Transaction,
  sendAndConfirmTransaction,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import {
  getAssociatedTokenAddressSync,
  createAssociatedTokenAccountInstruction,
  TOKEN_2022_PROGRAM_ID,
} from "@solana/spl-token";
import { Program, AnchorProvider, Wallet, BN } from "@coral-xyz/anchor";
import type {
  CreateParams,
  MintParams,
  BurnParams,
  FreezeParams,
  ThawParams,
  UpdateMinterParams,
  UpdateRolesParams,
  BlacklistAddParams,
  StablecoinConfig,
  RoleManager,
  ComplianceModule,
} from "./types";
import { Presets, getPresetConfig } from "./presets";
import {
  SSS_TOKEN_PROGRAM_ID,
  deriveConfigPda,
  deriveRolesPda,
  deriveBlacklistPda,
  deriveAllPdas,
} from "./constants";

// ── IDL import ─────────────────────────────────────────────────────────
// The IDL is generated by `anchor build`. Import it for typed instructions.
// We use a dynamic import pattern so the SDK works even without IDL.

/**
 * Main SDK client for the Solana Stablecoin Standard.
 *
 * ## Architecture
 *
 * The client wraps the on-chain `sss_token` Anchor program and provides:
 * - **Factory methods**: `create()` initializes a new stablecoin,
 *   `connect()` reconnects to an existing one
 * - **Operations**: `mint()`, `burn()`, `freeze()`, `thaw()`, `pause()`, `unpause()`
 * - **Role management**: `updateMinter()`, `removeMinter()`, `updateRoles()`, `transferAuthority()`
 * - **Queries**: `getConfig()`, `getRoles()`, `getTotalSupply()`
 * - **Compliance**: `compliance.blacklistAdd()`, `compliance.seize()`, etc.
 *
 * ## Key concept: the config PDA
 *
 * Every stablecoin has a **config PDA** derived from the mint address:
 * ```
 * seeds = ["config", mint.publicKey]
 * ```
 * This PDA is the **mint authority** and **freeze authority**, meaning
 * only the program can mint/freeze — and it checks roles before allowing it.
 *
 * @example
 * ```typescript
 * // Create a new SSS-2 stablecoin
 * const client = await SolanaStablecoin.create(connection, wallet, {
 *   preset: "SSS_2",
 *   name: "BRL Stable",
 *   symbol: "BRLs",
 *   decimals: 6,
 * });
 *
 * // Mint tokens
 * const tx = await client.mint({
 *   recipient: userPubkey,
 *   amount: BigInt(1_000_000),
 * });
 * ```
 */
export class SolanaStablecoin {
  /** The Solana connection */
  readonly connection: Connection;
  /** The config PDA address */
  readonly configPda: PublicKey;
  /** The config PDA bump */
  readonly configBump: number;
  /** The roles PDA address */
  readonly rolesPda: PublicKey;
  /** The roles PDA bump */
  readonly rolesBump: number;
  /** The Token-2022 mint address */
  readonly mintAddress: PublicKey;
  /** The signer wallet */
  readonly wallet: Wallet;
  /** The SSS program ID */
  readonly programId: PublicKey;

  private constructor(
    connection: Connection,
    mint: PublicKey,
    wallet: Wallet,
    programId: PublicKey = SSS_TOKEN_PROGRAM_ID
  ) {
    this.connection = connection;
    this.mintAddress = mint;
    this.wallet = wallet;
    this.programId = programId;

    const pdas = deriveAllPdas(mint, programId);
    this.configPda = pdas.configPda;
    this.configBump = pdas.configBump;
    this.rolesPda = pdas.rolesPda;
    this.rolesBump = pdas.rolesBump;
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Factory Methods
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Initialize a new stablecoin and return a connected client.
   *
   * This sends an `initialize` transaction that:
   * 1. Creates a Token-2022 mint with the right extensions
   * 2. Creates the config PDA (stores feature flags + metadata)
   * 3. Creates the role manager PDA (stores role assignments)
   *
   * @param connection - Solana RPC connection
   * @param wallet - The authority's wallet (payer + signer)
   * @param params - Creation parameters (preset, name, symbol, etc.)
   * @returns The connected client instance
   */
  static async create(
    connection: Connection,
    wallet: Wallet,
    params: CreateParams
  ): Promise<SolanaStablecoin> {
    // Resolve preset to extension config
    const extensions = params.preset
      ? getPresetConfig(params.preset as Presets)
      : params.extensions ?? {};

    // Generate a fresh mint keypair
    const mintKeypair = params.mintKeypair ?? Keypair.generate();

    // Build the client first to derive PDAs
    const client = new SolanaStablecoin(connection, mintKeypair.publicKey, wallet);

    // Build the initialize instruction
    // Anchor discriminator for "initialize" = first 8 bytes of sha256("global:initialize")
    const ix = await client.buildInitializeInstruction({
      name: params.name,
      symbol: params.symbol,
      uri: params.uri ?? "",
      decimals: params.decimals,
      enablePermanentDelegate: extensions.permanentDelegate ?? false,
      enableTransferHook: extensions.transferHook ?? false,
      enableConfidentialTransfers: extensions.confidentialTransfers ?? false,
      defaultAccountFrozen: extensions.defaultAccountFrozen ?? false,
      pauser: params.roles?.pauser ?? wallet.publicKey,
      blacklister: params.roles?.blacklister ?? null,
      seizer: params.roles?.seizer ?? null,
    }, mintKeypair);

    // Send the transaction
    const tx = new Transaction().add(ix);
    const sig = await sendAndConfirmTransaction(
      connection,
      tx,
      [wallet.payer, mintKeypair],
      { commitment: "confirmed" }
    );

    console.log(`✅ Stablecoin initialized: ${sig}`);
    console.log(`   Mint: ${mintKeypair.publicKey.toBase58()}`);
    console.log(`   Config: ${client.configPda.toBase58()}`);

    return client;
  }

  /**
   * Connect to an existing stablecoin by its mint address.
   * Does NOT send any transactions — just sets up the client.
   */
  static connect(
    connection: Connection,
    mint: PublicKey,
    wallet: Wallet,
    programId?: PublicKey
  ): SolanaStablecoin {
    return new SolanaStablecoin(connection, mint, wallet, programId);
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Core Operations
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Mint tokens to a recipient.
   *
   * The signer must be an authorized minter with available quota.
   * The config PDA signs the actual Token-2022 MintTo CPI on-chain.
   */
  async mint(params: MintParams): Promise<string> {
    const minter = params.minter ?? this.wallet.payer;
    const recipientAta = getAssociatedTokenAddressSync(
      this.mintAddress,
      params.recipient,
      false,
      TOKEN_2022_PROGRAM_ID
    );

    // Ensure ATA exists
    const ataInfo = await this.connection.getAccountInfo(recipientAta);
    const preIxs: TransactionInstruction[] = [];
    if (!ataInfo) {
      preIxs.push(
        createAssociatedTokenAccountInstruction(
          this.wallet.publicKey,
          recipientAta,
          params.recipient,
          this.mintAddress,
          TOKEN_2022_PROGRAM_ID
        )
      );
    }

    const ix = this.buildInstruction("mint_tokens", {
      amount: new BN(params.amount.toString()),
    }, {
      minter: minter.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
      mint: this.mintAddress,
      recipientTokenAccount: recipientAta,
      tokenProgram: TOKEN_2022_PROGRAM_ID,
    });

    const tx = new Transaction().add(...preIxs, ix);
    return sendAndConfirmTransaction(
      this.connection,
      tx,
      [this.wallet.payer, minter],
      { commitment: "confirmed" }
    );
  }

  /**
   * Burn tokens from the burner's token account.
   *
   * The signer must be an authorized burner.
   * Burns are tracked in `config.total_burned`.
   */
  async burn(params: BurnParams): Promise<string> {
    const burner = params.burner ?? this.wallet.payer;
    const burnerAta = getAssociatedTokenAddressSync(
      this.mintAddress,
      burner.publicKey,
      false,
      TOKEN_2022_PROGRAM_ID
    );

    const ix = this.buildInstruction("burn_tokens", {
      amount: new BN(params.amount.toString()),
    }, {
      burner: burner.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
      mint: this.mintAddress,
      burnerTokenAccount: burnerAta,
      tokenProgram: TOKEN_2022_PROGRAM_ID,
    });

    const tx = new Transaction().add(ix);
    return sendAndConfirmTransaction(
      this.connection,
      tx,
      [this.wallet.payer, burner],
      { commitment: "confirmed" }
    );
  }

  /**
   * Freeze a token account.
   *
   * The signer must be the master authority or pauser.
   * Once frozen, the account cannot send or receive tokens.
   */
  async freeze(params: FreezeParams): Promise<string> {
    const tokenAccount = getAssociatedTokenAddressSync(
      this.mintAddress,
      params.address,
      false,
      TOKEN_2022_PROGRAM_ID
    );

    const ix = this.buildInstruction("freeze_account", {}, {
      authority: this.wallet.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
      mint: this.mintAddress,
      tokenAccount,
      tokenProgram: TOKEN_2022_PROGRAM_ID,
    });

    const tx = new Transaction().add(ix);
    return sendAndConfirmTransaction(
      this.connection,
      tx,
      [this.wallet.payer],
      { commitment: "confirmed" }
    );
  }

  /**
   * Thaw (unfreeze) a token account.
   *
   * Only the master authority can thaw accounts.
   */
  async thaw(params: ThawParams): Promise<string> {
    const tokenAccount = getAssociatedTokenAddressSync(
      this.mintAddress,
      params.address,
      false,
      TOKEN_2022_PROGRAM_ID
    );

    const ix = this.buildInstruction("thaw_account", {}, {
      authority: this.wallet.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
      mint: this.mintAddress,
      tokenAccount,
      tokenProgram: TOKEN_2022_PROGRAM_ID,
    });

    const tx = new Transaction().add(ix);
    return sendAndConfirmTransaction(
      this.connection,
      tx,
      [this.wallet.payer],
      { commitment: "confirmed" }
    );
  }

  /**
   * Pause all mint/burn operations.
   *
   * The signer must be the master authority or pauser.
   * When paused, only freeze/thaw and role management still work.
   */
  async pause(): Promise<string> {
    const ix = this.buildInstruction("pause", {}, {
      pauser: this.wallet.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
    });

    const tx = new Transaction().add(ix);
    return sendAndConfirmTransaction(
      this.connection,
      tx,
      [this.wallet.payer],
      { commitment: "confirmed" }
    );
  }

  /**
   * Unpause operations.
   *
   * Only the master authority can unpause — the pauser intentionally
   * cannot unpause, as a safety measure (one person can stop, but
   * only the admin can restart).
   */
  async unpause(): Promise<string> {
    const ix = this.buildInstruction("unpause", {}, {
      authority: this.wallet.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
    });

    const tx = new Transaction().add(ix);
    return sendAndConfirmTransaction(
      this.connection,
      tx,
      [this.wallet.payer],
      { commitment: "confirmed" }
    );
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Role Management
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Add or update a minter with a quota.
   *
   * Only the master authority can manage minters.
   * Each minter has an independent quota — they can mint up to that amount.
   */
  async updateMinter(params: UpdateMinterParams): Promise<string> {
    const ix = this.buildInstruction("update_minter", {
      minter: params.minter,
      quota: new BN(params.quota.toString()),
    }, {
      authority: this.wallet.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
    });

    const tx = new Transaction().add(ix);
    return sendAndConfirmTransaction(
      this.connection,
      tx,
      [this.wallet.payer],
      { commitment: "confirmed" }
    );
  }

  /**
   * Remove a minter.
   */
  async removeMinter(minter: PublicKey): Promise<string> {
    const ix = this.buildInstruction("remove_minter", {
      minter,
    }, {
      authority: this.wallet.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
    });

    const tx = new Transaction().add(ix);
    return sendAndConfirmTransaction(
      this.connection,
      tx,
      [this.wallet.payer],
      { commitment: "confirmed" }
    );
  }

  /**
   * Update role assignments (pauser, blacklister, seizer, burners).
   */
  async updateRoles(params: UpdateRolesParams): Promise<string> {
    const ix = this.buildInstruction("update_roles", {
      params: {
        newPauser: params.newPauser ?? null,
        newBlacklister: params.newBlacklister ?? null,
        newSeizer: params.newSeizer ?? null,
        addBurner: params.addBurner ?? null,
        removeBurner: params.removeBurner ?? null,
      },
    }, {
      authority: this.wallet.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
    });

    const tx = new Transaction().add(ix);
    return sendAndConfirmTransaction(
      this.connection,
      tx,
      [this.wallet.payer],
      { commitment: "confirmed" }
    );
  }

  /**
   * Transfer master authority to a new address.
   *
   * ⚠️ This is irreversible — the new authority becomes the admin.
   */
  async transferAuthority(newAuthority: PublicKey): Promise<string> {
    const ix = this.buildInstruction("transfer_authority", {
      newAuthority,
    }, {
      authority: this.wallet.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
    });

    const tx = new Transaction().add(ix);
    return sendAndConfirmTransaction(
      this.connection,
      tx,
      [this.wallet.payer],
      { commitment: "confirmed" }
    );
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Queries
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Fetch the on-chain stablecoin configuration.
   */
  async getConfig(): Promise<StablecoinConfig> {
    const accountInfo = await this.connection.getAccountInfo(this.configPda);
    if (!accountInfo) {
      throw new Error(`Config account not found: ${this.configPda.toBase58()}`);
    }
    return this.deserializeConfig(accountInfo.data);
  }

  /**
   * Fetch the on-chain role assignments.
   */
  async getRoles(): Promise<RoleManager> {
    const accountInfo = await this.connection.getAccountInfo(this.rolesPda);
    if (!accountInfo) {
      throw new Error(`Roles account not found: ${this.rolesPda.toBase58()}`);
    }
    return this.deserializeRoles(accountInfo.data);
  }

  /**
   * Get the net token supply (totalMinted - totalBurned).
   */
  async getTotalSupply(): Promise<bigint> {
    const config = await this.getConfig();
    return config.totalMinted - config.totalBurned;
  }

  /**
   * Get the mint public key.
   */
  getMint(): PublicKey {
    return this.mintAddress;
  }

  /**
   * Get the config PDA public key.
   */
  getConfigPda(): PublicKey {
    return this.configPda;
  }

  /**
   * Get the roles PDA public key.
   */
  getRolesPda(): PublicKey {
    return this.rolesPda;
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Compliance Module (SSS-2)
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Compliance module for SSS-2 operations.
   *
   * These operations only work if the stablecoin was initialized with
   * `enablePermanentDelegate: true` and `enableTransferHook: true`.
   */
  readonly compliance: ComplianceModule = {
    /**
     * Add an address to the blacklist.
     * Creates a blacklist PDA on-chain. The signer must be the blacklister
     * or master authority.
     */
    blacklistAdd: async (params: BlacklistAddParams): Promise<string> => {
      const [blacklistPda] = deriveBlacklistPda(
        this.configPda,
        params.address,
        this.programId
      );

      const ix = this.buildInstruction("add_to_blacklist", {
        reason: params.reason,
      }, {
        blacklister: this.wallet.publicKey,
        config: this.configPda,
        roleManager: this.rolesPda,
        blacklistEntry: blacklistPda,
        addressToBlacklist: params.address,
        systemProgram: SystemProgram.programId,
      });

      const tx = new Transaction().add(ix);
      return sendAndConfirmTransaction(
        this.connection,
        tx,
        [this.wallet.payer],
        { commitment: "confirmed" }
      );
    },

    /**
     * Remove an address from the blacklist.
     * Closes the blacklist PDA and reclaims rent.
     */
    blacklistRemove: async (address: PublicKey): Promise<string> => {
      const [blacklistPda] = deriveBlacklistPda(
        this.configPda,
        address,
        this.programId
      );

      const ix = this.buildInstruction("remove_from_blacklist", {}, {
        blacklister: this.wallet.publicKey,
        config: this.configPda,
        roleManager: this.rolesPda,
        blacklistEntry: blacklistPda,
      });

      const tx = new Transaction().add(ix);
      return sendAndConfirmTransaction(
        this.connection,
        tx,
        [this.wallet.payer],
        { commitment: "confirmed" }
      );
    },

    /**
     * Check if an address is blacklisted.
     * Checks if the blacklist PDA exists on-chain.
     */
    isBlacklisted: async (address: PublicKey): Promise<boolean> => {
      const [blacklistPda] = deriveBlacklistPda(
        this.configPda,
        address,
        this.programId
      );
      const accountInfo = await this.connection.getAccountInfo(blacklistPda);
      return accountInfo !== null;
    },

    /**
     * Seize tokens from a frozen, blacklisted account.
     * Uses the permanent delegate authority to transfer tokens to treasury.
     */
    seize: async (from: PublicKey, treasury: PublicKey): Promise<string> => {
      const [blacklistPda] = deriveBlacklistPda(
        this.configPda,
        from,
        this.programId
      );

      const fromAta = getAssociatedTokenAddressSync(
        this.mintAddress,
        from,
        false,
        TOKEN_2022_PROGRAM_ID
      );

      const treasuryAta = getAssociatedTokenAddressSync(
        this.mintAddress,
        treasury,
        false,
        TOKEN_2022_PROGRAM_ID
      );

      const ix = this.buildInstruction("seize", {}, {
        seizer: this.wallet.publicKey,
        config: this.configPda,
        roleManager: this.rolesPda,
        blacklistEntry: blacklistPda,
        mint: this.mintAddress,
        fromTokenAccount: fromAta,
        treasuryTokenAccount: treasuryAta,
        tokenProgram: TOKEN_2022_PROGRAM_ID,
      });

      const tx = new Transaction().add(ix);
      return sendAndConfirmTransaction(
        this.connection,
        tx,
        [this.wallet.payer],
        { commitment: "confirmed" }
      );
    },
  };

  // ═══════════════════════════════════════════════════════════════════════
  // Internal Helpers
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Build a raw Anchor instruction.
   *
   * Uses the Anchor discriminator format: sha256("global:<method_name>")[0..8]
   * followed by borsh-serialized args.
   */
  private buildInstruction(
    _methodName: string,
    _args: Record<string, unknown>,
    accounts: Record<string, PublicKey>
  ): TransactionInstruction {
    // For now, we use the Anchor program object (loaded via IDL) to build instructions.
    // The actual implementation will use program.methods.<method>().accounts({...}).instruction()
    // This is a placeholder that creates the account metas for transaction construction.

    const keys = Object.entries(accounts).map(([name, pubkey]) => ({
      pubkey,
      isSigner: name === "authority" || name === "minter" || name === "burner" ||
        name === "pauser" || name === "blacklister" || name === "seizer",
      isWritable: name === "config" || name === "roleManager" || name === "mint" ||
        name === "recipientTokenAccount" || name === "burnerTokenAccount" ||
        name === "tokenAccount" || name === "blacklistEntry" ||
        name === "fromTokenAccount" || name === "treasuryTokenAccount" ||
        name === "authority" || name === "minter" || name === "burner" ||
        name === "pauser" || name === "blacklister" || name === "seizer",
    }));

    // Placeholder instruction data — will be replaced with proper Anchor serialization
    return new TransactionInstruction({
      programId: this.programId,
      keys,
      data: Buffer.alloc(0),
    });
  }

  /**
   * Build the initialize instruction (special case — needs mint keypair + more accounts).
   */
  private async buildInitializeInstruction(
    params: {
      name: string;
      symbol: string;
      uri: string;
      decimals: number;
      enablePermanentDelegate: boolean;
      enableTransferHook: boolean;
      enableConfidentialTransfers: boolean;
      defaultAccountFrozen: boolean;
      pauser: PublicKey;
      blacklister: PublicKey | null;
      seizer: PublicKey | null;
    },
    mintKeypair: Keypair,
  ): Promise<TransactionInstruction> {
    return this.buildInstruction("initialize", { params }, {
      authority: this.wallet.publicKey,
      config: this.configPda,
      roleManager: this.rolesPda,
      mint: mintKeypair.publicKey,
      tokenProgram: TOKEN_2022_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: SYSVAR_RENT_PUBKEY,
    });
  }

  /**
   * Deserialize a StablecoinConfig from raw account data.
   * Skips the 8-byte Anchor discriminator.
   */
  private deserializeConfig(data: Buffer): StablecoinConfig {
    let offset = 8; // Skip Anchor discriminator

    const authority = new PublicKey(data.subarray(offset, offset + 32));
    offset += 32;

    const mint = new PublicKey(data.subarray(offset, offset + 32));
    offset += 32;

    // String: 4-byte length prefix + data
    const nameLen = data.readUInt32LE(offset);
    offset += 4;
    const name = data.subarray(offset, offset + nameLen).toString("utf8");
    offset += nameLen;

    const symbolLen = data.readUInt32LE(offset);
    offset += 4;
    const symbol = data.subarray(offset, offset + symbolLen).toString("utf8");
    offset += symbolLen;

    const uriLen = data.readUInt32LE(offset);
    offset += 4;
    const uri = data.subarray(offset, offset + uriLen).toString("utf8");
    offset += uriLen;

    const decimals = data.readUInt8(offset);
    offset += 1;

    const isPaused = data.readUInt8(offset) === 1;
    offset += 1;

    const totalMinted = data.readBigUInt64LE(offset);
    offset += 8;

    const totalBurned = data.readBigUInt64LE(offset);
    offset += 8;

    const enablePermanentDelegate = data.readUInt8(offset) === 1;
    offset += 1;

    const enableTransferHook = data.readUInt8(offset) === 1;
    offset += 1;

    const enableConfidentialTransfers = data.readUInt8(offset) === 1;
    offset += 1;

    const defaultAccountFrozen = data.readUInt8(offset) === 1;
    offset += 1;

    const bump = data.readUInt8(offset);

    return {
      authority,
      mint,
      name,
      symbol,
      uri,
      decimals,
      isPaused,
      totalMinted,
      totalBurned,
      enablePermanentDelegate,
      enableTransferHook,
      enableConfidentialTransfers,
      defaultAccountFrozen,
      bump,
    };
  }

  /**
   * Deserialize a RoleManager from raw account data.
   * Skips the 8-byte Anchor discriminator.
   */
  private deserializeRoles(data: Buffer): RoleManager {
    let offset = 8; // Skip Anchor discriminator

    const config = new PublicKey(data.subarray(offset, offset + 32));
    offset += 32;

    const masterAuthority = new PublicKey(data.subarray(offset, offset + 32));
    offset += 32;

    const pauser = new PublicKey(data.subarray(offset, offset + 32));
    offset += 32;

    // Vec<MinterEntry>: 4-byte length + entries
    const mintersLen = data.readUInt32LE(offset);
    offset += 4;
    const minters = [];
    for (let i = 0; i < mintersLen; i++) {
      const address = new PublicKey(data.subarray(offset, offset + 32));
      offset += 32;
      const quota = data.readBigUInt64LE(offset);
      offset += 8;
      const minted = data.readBigUInt64LE(offset);
      offset += 8;
      minters.push({ address, quota, minted });
    }

    // Vec<Pubkey>: 4-byte length + pubkeys
    const burnersLen = data.readUInt32LE(offset);
    offset += 4;
    const burners = [];
    for (let i = 0; i < burnersLen; i++) {
      burners.push(new PublicKey(data.subarray(offset, offset + 32)));
      offset += 32;
    }

    const blacklister = new PublicKey(data.subarray(offset, offset + 32));
    offset += 32;

    const seizer = new PublicKey(data.subarray(offset, offset + 32));
    offset += 32;

    const bump = data.readUInt8(offset);

    return {
      config,
      masterAuthority,
      pauser,
      minters,
      burners,
      blacklister,
      seizer,
      bump,
    };
  }
}
