/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STABLECOIN_PROGRAM_ADDRESS } from "../programs";

export const SEIZE_DISCRIMINATOR = new Uint8Array([
  129, 159, 143, 31, 161, 224, 241, 84,
]);

export function getSeizeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(SEIZE_DISCRIMINATOR);
}

export type SeizeInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRoleConfig extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountFrom extends string | AccountMeta<string> = string,
  TAccountTo extends string | AccountMeta<string> = string,
  TAccountBlacklistEntry extends string | AccountMeta<string> = string,
  TAccountStablecoinProgram extends string | AccountMeta<string> =
    "Gbq8ZoZ4fE2J8wywFDYgSREPWL5qhtaneAX9PwQuQyCC",
  TAccountTransferHookProgram extends string | AccountMeta<string> = string,
  TAccountExtraAccountMetaList extends string | AccountMeta<string> = string,
  TAccountDestinationBlacklist extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRoleConfig extends string
        ? ReadonlyAccount<TAccountRoleConfig>
        : TAccountRoleConfig,
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountFrom extends string
        ? WritableAccount<TAccountFrom>
        : TAccountFrom,
      TAccountTo extends string ? WritableAccount<TAccountTo> : TAccountTo,
      TAccountBlacklistEntry extends string
        ? ReadonlyAccount<TAccountBlacklistEntry>
        : TAccountBlacklistEntry,
      TAccountStablecoinProgram extends string
        ? ReadonlyAccount<TAccountStablecoinProgram>
        : TAccountStablecoinProgram,
      TAccountTransferHookProgram extends string
        ? ReadonlyAccount<TAccountTransferHookProgram>
        : TAccountTransferHookProgram,
      TAccountExtraAccountMetaList extends string
        ? ReadonlyAccount<TAccountExtraAccountMetaList>
        : TAccountExtraAccountMetaList,
      TAccountDestinationBlacklist extends string
        ? ReadonlyAccount<TAccountDestinationBlacklist>
        : TAccountDestinationBlacklist,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >;

export type SeizeInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type SeizeInstructionDataArgs = { amount: number | bigint };

export function getSeizeInstructionDataEncoder(): FixedSizeEncoder<SeizeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: SEIZE_DISCRIMINATOR }),
  );
}

export function getSeizeInstructionDataDecoder(): FixedSizeDecoder<SeizeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getSeizeInstructionDataCodec(): FixedSizeCodec<
  SeizeInstructionDataArgs,
  SeizeInstructionData
> {
  return combineCodec(
    getSeizeInstructionDataEncoder(),
    getSeizeInstructionDataDecoder(),
  );
}

export type SeizeAsyncInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountRoleConfig extends string = string,
  TAccountMint extends string = string,
  TAccountFrom extends string = string,
  TAccountTo extends string = string,
  TAccountBlacklistEntry extends string = string,
  TAccountStablecoinProgram extends string = string,
  TAccountTransferHookProgram extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountDestinationBlacklist extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config?: Address<TAccountConfig>;
  roleConfig?: Address<TAccountRoleConfig>;
  mint: Address<TAccountMint>;
  from: Address<TAccountFrom>;
  to: Address<TAccountTo>;
  blacklistEntry: Address<TAccountBlacklistEntry>;
  stablecoinProgram?: Address<TAccountStablecoinProgram>;
  transferHookProgram: Address<TAccountTransferHookProgram>;
  extraAccountMetaList?: Address<TAccountExtraAccountMetaList>;
  destinationBlacklist: Address<TAccountDestinationBlacklist>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority?: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
  amount: SeizeInstructionDataArgs["amount"];
};

export async function getSeizeInstructionAsync<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountRoleConfig extends string,
  TAccountMint extends string,
  TAccountFrom extends string,
  TAccountTo extends string,
  TAccountBlacklistEntry extends string,
  TAccountStablecoinProgram extends string,
  TAccountTransferHookProgram extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountDestinationBlacklist extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof STABLECOIN_PROGRAM_ADDRESS,
>(
  input: SeizeAsyncInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountMint,
    TAccountFrom,
    TAccountTo,
    TAccountBlacklistEntry,
    TAccountStablecoinProgram,
    TAccountTransferHookProgram,
    TAccountExtraAccountMetaList,
    TAccountDestinationBlacklist,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  SeizeInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountMint,
    TAccountFrom,
    TAccountTo,
    TAccountBlacklistEntry,
    TAccountStablecoinProgram,
    TAccountTransferHookProgram,
    TAccountExtraAccountMetaList,
    TAccountDestinationBlacklist,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STABLECOIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
    roleConfig: { value: input.roleConfig ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: true },
    from: { value: input.from ?? null, isWritable: true },
    to: { value: input.to ?? null, isWritable: true },
    blacklistEntry: { value: input.blacklistEntry ?? null, isWritable: false },
    stablecoinProgram: {
      value: input.stablecoinProgram ?? null,
      isWritable: false,
    },
    transferHookProgram: {
      value: input.transferHookProgram ?? null,
      isWritable: false,
    },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: false,
    },
    destinationBlacklist: {
      value: input.destinationBlacklist ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("mint", accounts.mint.value),
        ),
      ],
    });
  }
  if (!accounts.roleConfig.value) {
    accounts.roleConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([114, 111, 108, 101, 115])),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("mint", accounts.mint.value),
        ),
      ],
    });
  }
  if (!accounts.stablecoinProgram.value) {
    accounts.stablecoinProgram.value =
      "Gbq8ZoZ4fE2J8wywFDYgSREPWL5qhtaneAX9PwQuQyCC" as Address<"Gbq8ZoZ4fE2J8wywFDYgSREPWL5qhtaneAX9PwQuQyCC">;
  }
  if (!accounts.extraAccountMetaList.value) {
    accounts.extraAccountMetaList.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            101, 120, 116, 114, 97, 45, 97, 99, 99, 111, 117, 110, 116, 45, 109,
            101, 116, 97, 115,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("mint", accounts.mint.value),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.eventAuthority.value) {
    accounts.eventAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114,
            105, 116, 121,
          ]),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("roleConfig", accounts.roleConfig),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("from", accounts.from),
      getAccountMeta("to", accounts.to),
      getAccountMeta("blacklistEntry", accounts.blacklistEntry),
      getAccountMeta("stablecoinProgram", accounts.stablecoinProgram),
      getAccountMeta("transferHookProgram", accounts.transferHookProgram),
      getAccountMeta("extraAccountMetaList", accounts.extraAccountMetaList),
      getAccountMeta("destinationBlacklist", accounts.destinationBlacklist),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
    ],
    data: getSeizeInstructionDataEncoder().encode(
      args as SeizeInstructionDataArgs,
    ),
    programAddress,
  } as SeizeInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountMint,
    TAccountFrom,
    TAccountTo,
    TAccountBlacklistEntry,
    TAccountStablecoinProgram,
    TAccountTransferHookProgram,
    TAccountExtraAccountMetaList,
    TAccountDestinationBlacklist,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram
  >);
}

export type SeizeInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountRoleConfig extends string = string,
  TAccountMint extends string = string,
  TAccountFrom extends string = string,
  TAccountTo extends string = string,
  TAccountBlacklistEntry extends string = string,
  TAccountStablecoinProgram extends string = string,
  TAccountTransferHookProgram extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountDestinationBlacklist extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  authority: TransactionSigner<TAccountAuthority>;
  config: Address<TAccountConfig>;
  roleConfig: Address<TAccountRoleConfig>;
  mint: Address<TAccountMint>;
  from: Address<TAccountFrom>;
  to: Address<TAccountTo>;
  blacklistEntry: Address<TAccountBlacklistEntry>;
  stablecoinProgram?: Address<TAccountStablecoinProgram>;
  transferHookProgram: Address<TAccountTransferHookProgram>;
  extraAccountMetaList: Address<TAccountExtraAccountMetaList>;
  destinationBlacklist: Address<TAccountDestinationBlacklist>;
  tokenProgram?: Address<TAccountTokenProgram>;
  eventAuthority: Address<TAccountEventAuthority>;
  program: Address<TAccountProgram>;
  amount: SeizeInstructionDataArgs["amount"];
};

export function getSeizeInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountRoleConfig extends string,
  TAccountMint extends string,
  TAccountFrom extends string,
  TAccountTo extends string,
  TAccountBlacklistEntry extends string,
  TAccountStablecoinProgram extends string,
  TAccountTransferHookProgram extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountDestinationBlacklist extends string,
  TAccountTokenProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof STABLECOIN_PROGRAM_ADDRESS,
>(
  input: SeizeInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountMint,
    TAccountFrom,
    TAccountTo,
    TAccountBlacklistEntry,
    TAccountStablecoinProgram,
    TAccountTransferHookProgram,
    TAccountExtraAccountMetaList,
    TAccountDestinationBlacklist,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): SeizeInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfig,
  TAccountRoleConfig,
  TAccountMint,
  TAccountFrom,
  TAccountTo,
  TAccountBlacklistEntry,
  TAccountStablecoinProgram,
  TAccountTransferHookProgram,
  TAccountExtraAccountMetaList,
  TAccountDestinationBlacklist,
  TAccountTokenProgram,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? STABLECOIN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: true },
    roleConfig: { value: input.roleConfig ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: true },
    from: { value: input.from ?? null, isWritable: true },
    to: { value: input.to ?? null, isWritable: true },
    blacklistEntry: { value: input.blacklistEntry ?? null, isWritable: false },
    stablecoinProgram: {
      value: input.stablecoinProgram ?? null,
      isWritable: false,
    },
    transferHookProgram: {
      value: input.transferHookProgram ?? null,
      isWritable: false,
    },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: false,
    },
    destinationBlacklist: {
      value: input.destinationBlacklist ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.stablecoinProgram.value) {
    accounts.stablecoinProgram.value =
      "Gbq8ZoZ4fE2J8wywFDYgSREPWL5qhtaneAX9PwQuQyCC" as Address<"Gbq8ZoZ4fE2J8wywFDYgSREPWL5qhtaneAX9PwQuQyCC">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("roleConfig", accounts.roleConfig),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("from", accounts.from),
      getAccountMeta("to", accounts.to),
      getAccountMeta("blacklistEntry", accounts.blacklistEntry),
      getAccountMeta("stablecoinProgram", accounts.stablecoinProgram),
      getAccountMeta("transferHookProgram", accounts.transferHookProgram),
      getAccountMeta("extraAccountMetaList", accounts.extraAccountMetaList),
      getAccountMeta("destinationBlacklist", accounts.destinationBlacklist),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("program", accounts.program),
    ],
    data: getSeizeInstructionDataEncoder().encode(
      args as SeizeInstructionDataArgs,
    ),
    programAddress,
  } as SeizeInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountRoleConfig,
    TAccountMint,
    TAccountFrom,
    TAccountTo,
    TAccountBlacklistEntry,
    TAccountStablecoinProgram,
    TAccountTransferHookProgram,
    TAccountExtraAccountMetaList,
    TAccountDestinationBlacklist,
    TAccountTokenProgram,
    TAccountEventAuthority,
    TAccountProgram
  >);
}

export type ParsedSeizeInstruction<
  TProgram extends string = typeof STABLECOIN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    authority: TAccountMetas[0];
    config: TAccountMetas[1];
    roleConfig: TAccountMetas[2];
    mint: TAccountMetas[3];
    from: TAccountMetas[4];
    to: TAccountMetas[5];
    blacklistEntry: TAccountMetas[6];
    stablecoinProgram: TAccountMetas[7];
    transferHookProgram: TAccountMetas[8];
    extraAccountMetaList: TAccountMetas[9];
    destinationBlacklist: TAccountMetas[10];
    tokenProgram: TAccountMetas[11];
    eventAuthority: TAccountMetas[12];
    program: TAccountMetas[13];
  };
  data: SeizeInstructionData;
};

export function parseSeizeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSeizeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 14) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 14,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      config: getNextAccount(),
      roleConfig: getNextAccount(),
      mint: getNextAccount(),
      from: getNextAccount(),
      to: getNextAccount(),
      blacklistEntry: getNextAccount(),
      stablecoinProgram: getNextAccount(),
      transferHookProgram: getNextAccount(),
      extraAccountMetaList: getNextAccount(),
      destinationBlacklist: getNextAccount(),
      tokenProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getSeizeInstructionDataDecoder().decode(instruction.data),
  };
}
