//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;
use trident_fuzz::AccountDiscriminator;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: sss_token
// ----------------------------------------------------------------------------
pub mod sss_token {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for sss_token
    pub fn program_id() -> Pubkey {
        pubkey!("6NMdvUa2n4WSLPx9yz7V9edFx9VQqWr5KUDZQGPK3GDL")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AcceptAuthority
    // ....................................................................

    /// Main instruction struct for AcceptAuthority
    pub struct AcceptAuthorityInstruction {
        pub accounts: AcceptAuthorityInstructionAccountMetas,
        pub data: AcceptAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AcceptAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct AcceptAuthorityInstructionAccountMetas {
        pub new_authority: AccountMeta,

        pub state: AccountMeta,
    }

    /// Account pubkeys for AcceptAuthority instruction
    #[derive(Debug, Clone)]
    pub struct AcceptAuthorityInstructionAccounts {
        pub new_authority: Pubkey,

        pub state: Pubkey,
    }

    impl AcceptAuthorityInstructionAccounts {
        pub fn new(new_authority: Pubkey, state: Pubkey) -> Self {
            Self {
                new_authority,

                state,
            }
        }
    }

    /// Instruction data for AcceptAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AcceptAuthorityInstructionData {}

    impl AcceptAuthorityInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for AcceptAuthorityInstruction
    impl AcceptAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [107u8, 86u8, 198u8, 91u8, 33u8, 12u8, 107u8, 160u8]
        }

        pub fn data(data: AcceptAuthorityInstructionData) -> Self {
            Self {
                accounts: AcceptAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AcceptAuthorityInstructionAccounts) -> Self {
            self.accounts.new_authority = AccountMeta::new_readonly(accounts.new_authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.new_authority.clone());

            metas.push(self.accounts.state.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: AddMinter
    // ....................................................................

    /// Main instruction struct for AddMinter
    pub struct AddMinterInstruction {
        pub accounts: AddMinterInstructionAccountMetas,
        pub data: AddMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddMinterInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,

        pub minter: AccountMeta,

        pub minter_info: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddMinter instruction
    #[derive(Debug, Clone)]
    pub struct AddMinterInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,

        pub minter: Pubkey,

        pub minter_info: Pubkey,
    }

    impl AddMinterInstructionAccounts {
        pub fn new(authority: Pubkey, state: Pubkey, minter: Pubkey, minter_info: Pubkey) -> Self {
            Self {
                authority,

                state,

                minter,

                minter_info,
            }
        }
    }

    /// Instruction data for AddMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddMinterInstructionData {
        pub quota: u64,
    }

    impl AddMinterInstructionData {
        pub fn new(quota: u64) -> Self {
            Self { quota }
        }
    }

    /// Implementation for AddMinterInstruction
    impl AddMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [75u8, 86u8, 218u8, 40u8, 219u8, 6u8, 141u8, 29u8]
        }

        pub fn data(data: AddMinterInstructionData) -> Self {
            Self {
                accounts: AddMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddMinterInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, false);

            self.accounts.minter_info = AccountMeta::new(accounts.minter_info, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: AddToBlacklist
    // ....................................................................

    /// Main instruction struct for AddToBlacklist
    pub struct AddToBlacklistInstruction {
        pub accounts: AddToBlacklistInstructionAccountMetas,
        pub data: AddToBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddToBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddToBlacklistInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,

        pub target: AccountMeta,

        pub blacklist_entry: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddToBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct AddToBlacklistInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,

        pub target: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl AddToBlacklistInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            state: Pubkey,

            target: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                authority,

                state,

                target,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for AddToBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddToBlacklistInstructionData {
        pub reason: String,
    }

    impl AddToBlacklistInstructionData {
        pub fn new(reason: String) -> Self {
            Self { reason }
        }
    }

    /// Implementation for AddToBlacklistInstruction
    impl AddToBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [90u8, 115u8, 98u8, 231u8, 173u8, 119u8, 117u8, 176u8]
        }

        pub fn data(data: AddToBlacklistInstructionData) -> Self {
            Self {
                accounts: AddToBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddToBlacklistInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self.accounts.target = AccountMeta::new_readonly(accounts.target, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.target.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Burn
    // ....................................................................

    /// Main instruction struct for Burn
    pub struct BurnInstruction {
        pub accounts: BurnInstructionAccountMetas,
        pub data: BurnInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Burn instruction
    #[derive(Debug, Clone, Default)]
    pub struct BurnInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,

        pub mint: AccountMeta,

        pub from_token_account: AccountMeta,

        pub permanent_delegate: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Burn instruction
    #[derive(Debug, Clone)]
    pub struct BurnInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,

        pub mint: Pubkey,

        pub from_token_account: Pubkey,

        pub permanent_delegate: Pubkey,
    }

    impl BurnInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            state: Pubkey,

            mint: Pubkey,

            from_token_account: Pubkey,

            permanent_delegate: Pubkey,
        ) -> Self {
            Self {
                authority,

                state,

                mint,

                from_token_account,

                permanent_delegate,
            }
        }
    }

    /// Instruction data for Burn
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BurnInstructionData {
        pub amount: u64,
    }

    impl BurnInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for BurnInstruction
    impl BurnInstruction {
        fn discriminator() -> [u8; 8] {
            [116u8, 110u8, 29u8, 56u8, 107u8, 219u8, 42u8, 93u8]
        }

        pub fn data(data: BurnInstructionData) -> Self {
            Self {
                accounts: BurnInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BurnInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.from_token_account = AccountMeta::new(accounts.from_token_account, false);

            self.accounts.permanent_delegate =
                AccountMeta::new_readonly(accounts.permanent_delegate, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.from_token_account.clone());

            metas.push(self.accounts.permanent_delegate.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FreezeAccount
    // ....................................................................

    /// Main instruction struct for FreezeAccount
    pub struct FreezeAccountInstruction {
        pub accounts: FreezeAccountInstructionAccountMetas,
        pub data: FreezeAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FreezeAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct FreezeAccountInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub freeze_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for FreezeAccount instruction
    #[derive(Debug, Clone)]
    pub struct FreezeAccountInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,

        pub freeze_authority: Pubkey,
    }

    impl FreezeAccountInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            state: Pubkey,

            mint: Pubkey,

            token_account: Pubkey,

            freeze_authority: Pubkey,
        ) -> Self {
            Self {
                authority,

                state,

                mint,

                token_account,

                freeze_authority,
            }
        }
    }

    /// Instruction data for FreezeAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FreezeAccountInstructionData {}

    impl FreezeAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for FreezeAccountInstruction
    impl FreezeAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [253u8, 75u8, 82u8, 133u8, 167u8, 238u8, 43u8, 130u8]
        }

        pub fn data(data: FreezeAccountInstructionData) -> Self {
            Self {
                accounts: FreezeAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FreezeAccountInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.state = AccountMeta::new_readonly(accounts.state, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.freeze_authority =
                AccountMeta::new_readonly(accounts.freeze_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.freeze_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: IncreaseMinterQuota
    // ....................................................................

    /// Main instruction struct for IncreaseMinterQuota
    pub struct IncreaseMinterQuotaInstruction {
        pub accounts: IncreaseMinterQuotaInstructionAccountMetas,
        pub data: IncreaseMinterQuotaInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for IncreaseMinterQuota instruction
    #[derive(Debug, Clone, Default)]
    pub struct IncreaseMinterQuotaInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,

        pub minter: AccountMeta,

        pub minter_info: AccountMeta,
    }

    /// Account pubkeys for IncreaseMinterQuota instruction
    #[derive(Debug, Clone)]
    pub struct IncreaseMinterQuotaInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,

        pub minter: Pubkey,

        pub minter_info: Pubkey,
    }

    impl IncreaseMinterQuotaInstructionAccounts {
        pub fn new(authority: Pubkey, state: Pubkey, minter: Pubkey, minter_info: Pubkey) -> Self {
            Self {
                authority,

                state,

                minter,

                minter_info,
            }
        }
    }

    /// Instruction data for IncreaseMinterQuota
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct IncreaseMinterQuotaInstructionData {
        pub additional_quota: u64,
    }

    impl IncreaseMinterQuotaInstructionData {
        pub fn new(additional_quota: u64) -> Self {
            Self { additional_quota }
        }
    }

    /// Implementation for IncreaseMinterQuotaInstruction
    impl IncreaseMinterQuotaInstruction {
        fn discriminator() -> [u8; 8] {
            [102u8, 87u8, 42u8, 217u8, 237u8, 250u8, 91u8, 70u8]
        }

        pub fn data(data: IncreaseMinterQuotaInstructionData) -> Self {
            Self {
                accounts: IncreaseMinterQuotaInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: IncreaseMinterQuotaInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, false);

            self.accounts.minter_info = AccountMeta::new(accounts.minter_info, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub master_authority: AccountMeta,

        pub state: AccountMeta,

        pub mint: AccountMeta,

        pub system_program: AccountMeta,

        pub token_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub master_authority: Pubkey,

        pub state: Pubkey,

        pub mint: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(master_authority: Pubkey, state: Pubkey, mint: Pubkey) -> Self {
            Self {
                master_authority,

                state,

                mint,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub config: StablecoinConfig,
    }

    impl InitializeInstructionData {
        pub fn new(config: StablecoinConfig) -> Self {
            Self { config }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.master_authority = AccountMeta::new(accounts.master_authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.master_authority.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Mint
    // ....................................................................

    /// Main instruction struct for Mint
    pub struct MintInstruction {
        pub accounts: MintInstructionAccountMetas,
        pub data: MintInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Mint instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintInstructionAccountMetas {
        pub minter: AccountMeta,

        pub state: AccountMeta,

        pub mint: AccountMeta,

        pub minter_info: AccountMeta,

        pub recipient_token_account: AccountMeta,

        pub mint_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Mint instruction
    #[derive(Debug, Clone)]
    pub struct MintInstructionAccounts {
        pub minter: Pubkey,

        pub state: Pubkey,

        pub mint: Pubkey,

        pub minter_info: Pubkey,

        pub recipient_token_account: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl MintInstructionAccounts {
        pub fn new(
            minter: Pubkey,

            state: Pubkey,

            mint: Pubkey,

            minter_info: Pubkey,

            recipient_token_account: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                minter,

                state,

                mint,

                minter_info,

                recipient_token_account,

                mint_authority,
            }
        }
    }

    /// Instruction data for Mint
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintInstructionData {
        pub amount: u64,
    }

    impl MintInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintInstruction
    impl MintInstruction {
        fn discriminator() -> [u8; 8] {
            [51u8, 57u8, 225u8, 47u8, 182u8, 146u8, 137u8, 166u8]
        }

        pub fn data(data: MintInstructionData) -> Self {
            Self {
                accounts: MintInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintInstructionAccounts) -> Self {
            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.minter_info = AccountMeta::new(accounts.minter_info, false);

            self.accounts.recipient_token_account =
                AccountMeta::new(accounts.recipient_token_account, false);

            self.accounts.mint_authority =
                AccountMeta::new_readonly(accounts.mint_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.push(self.accounts.recipient_token_account.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pause
    // ....................................................................

    /// Main instruction struct for Pause
    pub struct PauseInstruction {
        pub accounts: PauseInstructionAccountMetas,
        pub data: PauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pause instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,
    }

    /// Account pubkeys for Pause instruction
    #[derive(Debug, Clone)]
    pub struct PauseInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,
    }

    impl PauseInstructionAccounts {
        pub fn new(authority: Pubkey, state: Pubkey) -> Self {
            Self { authority, state }
        }
    }

    /// Instruction data for Pause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseInstructionData {}

    impl PauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseInstruction
    impl PauseInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 22u8, 221u8, 251u8, 74u8, 121u8, 193u8, 47u8]
        }

        pub fn data(data: PauseInstructionData) -> Self {
            Self {
                accounts: PauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ProposeAuthority
    // ....................................................................

    /// Main instruction struct for ProposeAuthority
    pub struct ProposeAuthorityInstruction {
        pub accounts: ProposeAuthorityInstructionAccountMetas,
        pub data: ProposeAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ProposeAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct ProposeAuthorityInstructionAccountMetas {
        pub current_authority: AccountMeta,

        pub proposed_authority: AccountMeta,

        pub state: AccountMeta,
    }

    /// Account pubkeys for ProposeAuthority instruction
    #[derive(Debug, Clone)]
    pub struct ProposeAuthorityInstructionAccounts {
        pub current_authority: Pubkey,

        pub proposed_authority: Pubkey,

        pub state: Pubkey,
    }

    impl ProposeAuthorityInstructionAccounts {
        pub fn new(current_authority: Pubkey, proposed_authority: Pubkey, state: Pubkey) -> Self {
            Self {
                current_authority,

                proposed_authority,

                state,
            }
        }
    }

    /// Instruction data for ProposeAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ProposeAuthorityInstructionData {}

    impl ProposeAuthorityInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ProposeAuthorityInstruction
    impl ProposeAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [20u8, 148u8, 236u8, 198u8, 76u8, 119u8, 99u8, 142u8]
        }

        pub fn data(data: ProposeAuthorityInstructionData) -> Self {
            Self {
                accounts: ProposeAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ProposeAuthorityInstructionAccounts) -> Self {
            self.accounts.current_authority =
                AccountMeta::new_readonly(accounts.current_authority, true);

            self.accounts.proposed_authority =
                AccountMeta::new_readonly(accounts.proposed_authority, false);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.current_authority.clone());

            metas.push(self.accounts.proposed_authority.clone());

            metas.push(self.accounts.state.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveFromBlacklist
    // ....................................................................

    /// Main instruction struct for RemoveFromBlacklist
    pub struct RemoveFromBlacklistInstruction {
        pub accounts: RemoveFromBlacklistInstructionAccountMetas,
        pub data: RemoveFromBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveFromBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveFromBlacklistInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,

        pub target: AccountMeta,

        pub blacklist_entry: AccountMeta,
    }

    /// Account pubkeys for RemoveFromBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct RemoveFromBlacklistInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,

        pub target: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl RemoveFromBlacklistInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            state: Pubkey,

            target: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                authority,

                state,

                target,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for RemoveFromBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveFromBlacklistInstructionData {
        pub reason: String,
    }

    impl RemoveFromBlacklistInstructionData {
        pub fn new(reason: String) -> Self {
            Self { reason }
        }
    }

    /// Implementation for RemoveFromBlacklistInstruction
    impl RemoveFromBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [47u8, 105u8, 20u8, 10u8, 165u8, 168u8, 203u8, 219u8]
        }

        pub fn data(data: RemoveFromBlacklistInstructionData) -> Self {
            Self {
                accounts: RemoveFromBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveFromBlacklistInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self.accounts.target = AccountMeta::new_readonly(accounts.target, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.target.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveMinter
    // ....................................................................

    /// Main instruction struct for RemoveMinter
    pub struct RemoveMinterInstruction {
        pub accounts: RemoveMinterInstructionAccountMetas,
        pub data: RemoveMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveMinterInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,

        pub minter: AccountMeta,

        pub minter_info: AccountMeta,
    }

    /// Account pubkeys for RemoveMinter instruction
    #[derive(Debug, Clone)]
    pub struct RemoveMinterInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,

        pub minter: Pubkey,

        pub minter_info: Pubkey,
    }

    impl RemoveMinterInstructionAccounts {
        pub fn new(authority: Pubkey, state: Pubkey, minter: Pubkey, minter_info: Pubkey) -> Self {
            Self {
                authority,

                state,

                minter,

                minter_info,
            }
        }
    }

    /// Instruction data for RemoveMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveMinterInstructionData {}

    impl RemoveMinterInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RemoveMinterInstruction
    impl RemoveMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [241u8, 69u8, 84u8, 16u8, 164u8, 232u8, 131u8, 79u8]
        }

        pub fn data(data: RemoveMinterInstructionData) -> Self {
            Self {
                accounts: RemoveMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveMinterInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, false);

            self.accounts.minter_info = AccountMeta::new(accounts.minter_info, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Seize
    // ....................................................................

    /// Main instruction struct for Seize
    pub struct SeizeInstruction {
        pub accounts: SeizeInstructionAccountMetas,
        pub data: SeizeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Seize instruction
    #[derive(Debug, Clone, Default)]
    pub struct SeizeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,

        pub mint: AccountMeta,

        pub target_wallet: AccountMeta,

        pub blacklist_entry: AccountMeta,

        pub from_token_account: AccountMeta,

        pub treasury_token_account: AccountMeta,

        pub permanent_delegate: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Seize instruction
    #[derive(Debug, Clone)]
    pub struct SeizeInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,

        pub mint: Pubkey,

        pub target_wallet: Pubkey,

        pub blacklist_entry: Pubkey,

        pub from_token_account: Pubkey,

        pub treasury_token_account: Pubkey,

        pub permanent_delegate: Pubkey,
    }

    impl SeizeInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            state: Pubkey,

            mint: Pubkey,

            target_wallet: Pubkey,

            blacklist_entry: Pubkey,

            from_token_account: Pubkey,

            treasury_token_account: Pubkey,

            permanent_delegate: Pubkey,
        ) -> Self {
            Self {
                authority,

                state,

                mint,

                target_wallet,

                blacklist_entry,

                from_token_account,

                treasury_token_account,

                permanent_delegate,
            }
        }
    }

    /// Instruction data for Seize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SeizeInstructionData {}

    impl SeizeInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SeizeInstruction
    impl SeizeInstruction {
        fn discriminator() -> [u8; 8] {
            [129u8, 159u8, 143u8, 31u8, 161u8, 224u8, 241u8, 84u8]
        }

        pub fn data(data: SeizeInstructionData) -> Self {
            Self {
                accounts: SeizeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SeizeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.state = AccountMeta::new_readonly(accounts.state, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.target_wallet = AccountMeta::new_readonly(accounts.target_wallet, false);

            self.accounts.blacklist_entry =
                AccountMeta::new_readonly(accounts.blacklist_entry, false);

            self.accounts.from_token_account = AccountMeta::new(accounts.from_token_account, false);

            self.accounts.treasury_token_account =
                AccountMeta::new(accounts.treasury_token_account, false);

            self.accounts.permanent_delegate =
                AccountMeta::new_readonly(accounts.permanent_delegate, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.target_wallet.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.push(self.accounts.from_token_account.clone());

            metas.push(self.accounts.treasury_token_account.clone());

            metas.push(self.accounts.permanent_delegate.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ThawAccount
    // ....................................................................

    /// Main instruction struct for ThawAccount
    pub struct ThawAccountInstruction {
        pub accounts: ThawAccountInstructionAccountMetas,
        pub data: ThawAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ThawAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct ThawAccountInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub freeze_authority: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ThawAccount instruction
    #[derive(Debug, Clone)]
    pub struct ThawAccountInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,

        pub freeze_authority: Pubkey,
    }

    impl ThawAccountInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            state: Pubkey,

            mint: Pubkey,

            token_account: Pubkey,

            freeze_authority: Pubkey,
        ) -> Self {
            Self {
                authority,

                state,

                mint,

                token_account,

                freeze_authority,
            }
        }
    }

    /// Instruction data for ThawAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ThawAccountInstructionData {}

    impl ThawAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ThawAccountInstruction
    impl ThawAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [115u8, 152u8, 79u8, 213u8, 213u8, 169u8, 184u8, 35u8]
        }

        pub fn data(data: ThawAccountInstructionData) -> Self {
            Self {
                accounts: ThawAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ThawAccountInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.state = AccountMeta::new_readonly(accounts.state, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.freeze_authority =
                AccountMeta::new_readonly(accounts.freeze_authority, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.freeze_authority.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Unpause
    // ....................................................................

    /// Main instruction struct for Unpause
    pub struct UnpauseInstruction {
        pub accounts: UnpauseInstructionAccountMetas,
        pub data: UnpauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Unpause instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpauseInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,
    }

    /// Account pubkeys for Unpause instruction
    #[derive(Debug, Clone)]
    pub struct UnpauseInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,
    }

    impl UnpauseInstructionAccounts {
        pub fn new(authority: Pubkey, state: Pubkey) -> Self {
            Self { authority, state }
        }
    }

    /// Instruction data for Unpause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpauseInstructionData {}

    impl UnpauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpauseInstruction
    impl UnpauseInstruction {
        fn discriminator() -> [u8; 8] {
            [169u8, 144u8, 4u8, 38u8, 10u8, 141u8, 188u8, 255u8]
        }

        pub fn data(data: UnpauseInstructionData) -> Self {
            Self {
                accounts: UnpauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpauseInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateRoles
    // ....................................................................

    /// Main instruction struct for UpdateRoles
    pub struct UpdateRolesInstruction {
        pub accounts: UpdateRolesInstructionAccountMetas,
        pub data: UpdateRolesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateRoles instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateRolesInstructionAccountMetas {
        pub authority: AccountMeta,

        pub state: AccountMeta,
    }

    /// Account pubkeys for UpdateRoles instruction
    #[derive(Debug, Clone)]
    pub struct UpdateRolesInstructionAccounts {
        pub authority: Pubkey,

        pub state: Pubkey,
    }

    impl UpdateRolesInstructionAccounts {
        pub fn new(authority: Pubkey, state: Pubkey) -> Self {
            Self { authority, state }
        }
    }

    /// Instruction data for UpdateRoles
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateRolesInstructionData {
        pub role_update: RoleUpdate,
    }

    impl UpdateRolesInstructionData {
        pub fn new(role_update: RoleUpdate) -> Self {
            Self { role_update }
        }
    }

    /// Implementation for UpdateRolesInstruction
    impl UpdateRolesInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 152u8, 205u8, 233u8, 177u8, 123u8, 219u8, 125u8]
        }

        pub fn data(data: UpdateRolesInstructionData) -> Self {
            Self {
                accounts: UpdateRolesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateRolesInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.state = AccountMeta::new(accounts.state, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.state.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Data Accounts (with discriminators)
    // ------------------------------------------------------------------------

    /// AccountDiscriminator implementation for BlacklistEntry
    impl AccountDiscriminator for BlacklistEntry {
        fn discriminator() -> &'static [u8] {
            &[218u8, 179u8, 231u8, 40u8, 141u8, 25u8, 168u8, 189u8]
        }
    }

    /// AccountDiscriminator implementation for MinterInfo
    impl AccountDiscriminator for MinterInfo {
        fn discriminator() -> &'static [u8] {
            &[158u8, 4u8, 176u8, 199u8, 251u8, 15u8, 209u8, 131u8]
        }
    }

    /// AccountDiscriminator implementation for StablecoinState
    impl AccountDiscriminator for StablecoinState {
        fn discriminator() -> &'static [u8] {
            &[107u8, 33u8, 134u8, 54u8, 129u8, 13u8, 187u8, 151u8]
        }
    }

    // ------------------------------------------------------------------------
    // Errors
    // ------------------------------------------------------------------------

    /// Program errors for sss_token
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum SsstokenError {
        /// Unauthorized: caller does not hold required role
        Unauthorized = 6000,

        /// No pending authority transfer
        NoPendingAuthority = 6001,

        /// Only the pending authority can accept this transfer
        WrongPendingAuthority = 6002,

        /// Protocol is paused — all minting and burning is suspended
        ProtocolPaused = 6003,

        /// Minter is inactive or has been removed
        MinterInactive = 6004,

        /// Minter quota exceeded — request amount is above remaining lifetime
        /// quota
        QuotaExceeded = 6005,

        /// Cannot increase quota for an unlimited minter
        CannotIncreaseUnlimitedQuota = 6006,

        /// Compliance module is not enabled on this stablecoin
        ComplianceNotEnabled = 6007,

        /// Address is already on the blacklist
        AlreadyBlacklisted = 6008,

        /// Address is not on the blacklist
        NotBlacklisted = 6009,

        /// Cannot seize tokens — account is not blacklisted
        SeizeRequiresBlacklist = 6010,

        /// Permanent delegate not enabled — seize is unavailable
        PermanentDelegateNotEnabled = 6011,

        /// Transfer blocked — sender is blacklisted
        SenderBlacklisted = 6012,

        /// Transfer blocked — recipient is blacklisted
        RecipientBlacklisted = 6013,

        /// Amount must be greater than zero
        ZeroAmount = 6014,

        /// String field exceeds maximum length
        StringTooLong = 6015,

        /// Arithmetic overflow
        Overflow = 6016,

        /// Minter not found
        MinterNotFound = 6017,

        /// Minter is already inactive
        MinterAlreadyInactive = 6018,
    }

    impl SsstokenError {
        /// Get the error code
        pub fn code(&self) -> u32 {
            *self as u32
        }

        /// Get the error message
        pub fn msg(&self) -> &'static str {
            match self {
                Self::Unauthorized => "Unauthorized: caller does not hold required role",

                Self::NoPendingAuthority => "No pending authority transfer",

                Self::WrongPendingAuthority => {
                    "Only the pending authority can accept this transfer"
                }

                Self::ProtocolPaused => "Protocol is paused — all minting and burning is suspended",

                Self::MinterInactive => "Minter is inactive or has been removed",

                Self::QuotaExceeded => {
                    "Minter quota exceeded — request amount is above remaining lifetime quota"
                }

                Self::CannotIncreaseUnlimitedQuota => {
                    "Cannot increase quota for an unlimited minter"
                }

                Self::ComplianceNotEnabled => "Compliance module is not enabled on this stablecoin",

                Self::AlreadyBlacklisted => "Address is already on the blacklist",

                Self::NotBlacklisted => "Address is not on the blacklist",

                Self::SeizeRequiresBlacklist => "Cannot seize tokens — account is not blacklisted",

                Self::PermanentDelegateNotEnabled => {
                    "Permanent delegate not enabled — seize is unavailable"
                }

                Self::SenderBlacklisted => "Transfer blocked — sender is blacklisted",

                Self::RecipientBlacklisted => "Transfer blocked — recipient is blacklisted",

                Self::ZeroAmount => "Amount must be greater than zero",

                Self::StringTooLong => "String field exceeds maximum length",

                Self::Overflow => "Arithmetic overflow",

                Self::MinterNotFound => "Minter not found",

                Self::MinterAlreadyInactive => "Minter is already inactive",
            }
        }

        /// Try to convert from error code
        pub fn from_code(code: u32) -> Option<Self> {
            match code {
                6000 => Some(Self::Unauthorized),

                6001 => Some(Self::NoPendingAuthority),

                6002 => Some(Self::WrongPendingAuthority),

                6003 => Some(Self::ProtocolPaused),

                6004 => Some(Self::MinterInactive),

                6005 => Some(Self::QuotaExceeded),

                6006 => Some(Self::CannotIncreaseUnlimitedQuota),

                6007 => Some(Self::ComplianceNotEnabled),

                6008 => Some(Self::AlreadyBlacklisted),

                6009 => Some(Self::NotBlacklisted),

                6010 => Some(Self::SeizeRequiresBlacklist),

                6011 => Some(Self::PermanentDelegateNotEnabled),

                6012 => Some(Self::SenderBlacklisted),

                6013 => Some(Self::RecipientBlacklisted),

                6014 => Some(Self::ZeroAmount),

                6015 => Some(Self::StringTooLong),

                6016 => Some(Self::Overflow),

                6017 => Some(Self::MinterNotFound),

                6018 => Some(Self::MinterAlreadyInactive),

                _ => None,
            }
        }
    }

    impl std::fmt::Display for SsstokenError {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{}: {}", self.code(), self.msg())
        }
    }

    impl std::error::Error for SsstokenError {}

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Custom Types
    // ------------------------------------------------------------------------

    /// Custom struct: AccountFrozen
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct AccountFrozen {
        pub mint: Pubkey,

        pub account: Pubkey,

        pub authority: Pubkey,

        pub timestamp: i64,
    }

    impl AccountFrozen {
        pub fn new(mint: Pubkey, account: Pubkey, authority: Pubkey, timestamp: i64) -> Self {
            Self {
                mint,

                account,

                authority,

                timestamp,
            }
        }
    }

    /// Custom struct: AccountThawed
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct AccountThawed {
        pub mint: Pubkey,

        pub account: Pubkey,

        pub authority: Pubkey,

        pub timestamp: i64,
    }

    impl AccountThawed {
        pub fn new(mint: Pubkey, account: Pubkey, authority: Pubkey, timestamp: i64) -> Self {
            Self {
                mint,

                account,

                authority,

                timestamp,
            }
        }
    }

    /// Custom struct: AddressBlacklisted
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct AddressBlacklisted {
        pub mint: Pubkey,

        pub address: Pubkey,

        pub reason: String,

        pub blacklister: Pubkey,

        pub timestamp: i64,
    }

    impl AddressBlacklisted {
        pub fn new(
            mint: Pubkey,

            address: Pubkey,

            reason: String,

            blacklister: Pubkey,

            timestamp: i64,
        ) -> Self {
            Self {
                mint,

                address,

                reason,

                blacklister,

                timestamp,
            }
        }
    }

    /// Custom struct: AddressUnblacklisted
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct AddressUnblacklisted {
        pub mint: Pubkey,

        pub address: Pubkey,

        pub reason: String,

        pub blacklister: Pubkey,

        pub timestamp: i64,
    }

    impl AddressUnblacklisted {
        pub fn new(
            mint: Pubkey,

            address: Pubkey,

            reason: String,

            blacklister: Pubkey,

            timestamp: i64,
        ) -> Self {
            Self {
                mint,

                address,

                reason,

                blacklister,

                timestamp,
            }
        }
    }

    /// Custom struct: AuthorityProposed
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct AuthorityProposed {
        pub mint: Pubkey,

        pub current: Pubkey,

        pub proposed: Pubkey,

        pub timestamp: i64,
    }

    impl AuthorityProposed {
        pub fn new(mint: Pubkey, current: Pubkey, proposed: Pubkey, timestamp: i64) -> Self {
            Self {
                mint,

                current,

                proposed,

                timestamp,
            }
        }
    }

    /// Custom struct: AuthorityTransferred
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct AuthorityTransferred {
        pub mint: Pubkey,

        pub old_authority: Pubkey,

        pub new_authority: Pubkey,

        pub timestamp: i64,
    }

    impl AuthorityTransferred {
        pub fn new(
            mint: Pubkey,

            old_authority: Pubkey,

            new_authority: Pubkey,

            timestamp: i64,
        ) -> Self {
            Self {
                mint,

                old_authority,

                new_authority,

                timestamp,
            }
        }
    }

    /// Custom struct: BlacklistEntry
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct BlacklistEntry {
        pub stablecoin: Pubkey,

        pub address: Pubkey,

        pub reason: String,

        pub added_at: i64,

        pub added_by: Pubkey,

        pub active: bool,

        pub bump: u8,
    }

    impl BlacklistEntry {
        pub fn new(
            stablecoin: Pubkey,

            address: Pubkey,

            reason: String,

            added_at: i64,

            added_by: Pubkey,

            active: bool,

            bump: u8,
        ) -> Self {
            Self {
                stablecoin,

                address,

                reason,

                added_at,

                added_by,

                active,

                bump,
            }
        }
    }

    /// Custom struct: MinterInfo
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct MinterInfo {
        pub stablecoin: Pubkey,

        pub minter: Pubkey,

        pub quota: u64,

        pub minted_total: u64,

        pub active: bool,

        pub bump: u8,
    }

    impl MinterInfo {
        pub fn new(
            stablecoin: Pubkey,

            minter: Pubkey,

            quota: u64,

            minted_total: u64,

            active: bool,

            bump: u8,
        ) -> Self {
            Self {
                stablecoin,

                minter,

                quota,

                minted_total,

                active,

                bump,
            }
        }
    }

    /// Custom struct: MinterUpdated
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct MinterUpdated {
        pub mint: Pubkey,

        pub minter: Pubkey,

        pub quota: u64,

        pub active: bool,

        pub authority: Pubkey,

        pub timestamp: i64,
    }

    impl MinterUpdated {
        pub fn new(
            mint: Pubkey,

            minter: Pubkey,

            quota: u64,

            active: bool,

            authority: Pubkey,

            timestamp: i64,
        ) -> Self {
            Self {
                mint,

                minter,

                quota,

                active,

                authority,

                timestamp,
            }
        }
    }

    /// Custom struct: ProtocolPaused
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct ProtocolPaused {
        pub mint: Pubkey,

        pub pauser: Pubkey,

        pub timestamp: i64,
    }

    impl ProtocolPaused {
        pub fn new(mint: Pubkey, pauser: Pubkey, timestamp: i64) -> Self {
            Self {
                mint,

                pauser,

                timestamp,
            }
        }
    }

    /// Custom struct: ProtocolUnpaused
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct ProtocolUnpaused {
        pub mint: Pubkey,

        pub pauser: Pubkey,

        pub timestamp: i64,
    }

    impl ProtocolUnpaused {
        pub fn new(mint: Pubkey, pauser: Pubkey, timestamp: i64) -> Self {
            Self {
                mint,

                pauser,

                timestamp,
            }
        }
    }

    /// Custom struct: RoleUpdate
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct RoleUpdate {
        pub pauser: Option<Pubkey>,

        pub freezer: Option<Pubkey>,

        pub burner: Option<Pubkey>,

        pub blacklister: Option<Pubkey>,

        pub seizer: Option<Pubkey>,
    }

    impl RoleUpdate {
        pub fn new(
            pauser: Option<Pubkey>,

            freezer: Option<Pubkey>,

            burner: Option<Pubkey>,

            blacklister: Option<Pubkey>,

            seizer: Option<Pubkey>,
        ) -> Self {
            Self {
                pauser,

                freezer,

                burner,

                blacklister,

                seizer,
            }
        }
    }

    /// Custom struct: RolesUpdated
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct RolesUpdated {
        pub mint: Pubkey,

        pub authority: Pubkey,

        pub timestamp: i64,
    }

    impl RolesUpdated {
        pub fn new(mint: Pubkey, authority: Pubkey, timestamp: i64) -> Self {
            Self {
                mint,

                authority,

                timestamp,
            }
        }
    }

    /// Custom struct: StablecoinConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct StablecoinConfig {
        pub name: String,

        pub symbol: String,

        pub uri: String,

        pub decimals: u8,

        pub enable_permanent_delegate: bool,

        pub enable_transfer_hook: bool,

        pub default_account_frozen: bool,

        pub transfer_hook_program_id: Option<Pubkey>,
    }

    impl StablecoinConfig {
        pub fn new(
            name: String,

            symbol: String,

            uri: String,

            decimals: u8,

            enable_permanent_delegate: bool,

            enable_transfer_hook: bool,

            default_account_frozen: bool,

            transfer_hook_program_id: Option<Pubkey>,
        ) -> Self {
            Self {
                name,

                symbol,

                uri,

                decimals,

                enable_permanent_delegate,

                enable_transfer_hook,

                default_account_frozen,

                transfer_hook_program_id,
            }
        }
    }

    /// Custom struct: StablecoinInitialized
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct StablecoinInitialized {
        pub mint: Pubkey,

        pub master_authority: Pubkey,

        pub name: String,

        pub symbol: String,

        pub decimals: u8,

        pub compliance_enabled: bool,

        pub timestamp: i64,
    }

    impl StablecoinInitialized {
        pub fn new(
            mint: Pubkey,

            master_authority: Pubkey,

            name: String,

            symbol: String,

            decimals: u8,

            compliance_enabled: bool,

            timestamp: i64,
        ) -> Self {
            Self {
                mint,

                master_authority,

                name,

                symbol,

                decimals,

                compliance_enabled,

                timestamp,
            }
        }
    }

    /// Custom struct: StablecoinState
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct StablecoinState {
        pub master_authority: Pubkey,

        pub pending_authority: Option<Pubkey>,

        pub mint: Pubkey,

        pub name: String,

        pub symbol: String,

        pub uri: String,

        pub decimals: u8,

        pub compliance_enabled: bool,

        pub permanent_delegate_enabled: bool,

        pub transfer_hook_enabled: bool,

        pub default_account_frozen: bool,

        pub paused: bool,

        pub total_minted: u64,

        pub total_burned: u64,

        pub pauser: Option<Pubkey>,

        pub freezer: Option<Pubkey>,

        pub burner: Option<Pubkey>,

        pub blacklister: Option<Pubkey>,

        pub seizer: Option<Pubkey>,

        pub transfer_hook_program_id: Option<Pubkey>,

        pub bump: u8,
    }

    impl StablecoinState {
        pub fn new(
            master_authority: Pubkey,

            pending_authority: Option<Pubkey>,

            mint: Pubkey,

            name: String,

            symbol: String,

            uri: String,

            decimals: u8,

            compliance_enabled: bool,

            permanent_delegate_enabled: bool,

            transfer_hook_enabled: bool,

            default_account_frozen: bool,

            paused: bool,

            total_minted: u64,

            total_burned: u64,

            pauser: Option<Pubkey>,

            freezer: Option<Pubkey>,

            burner: Option<Pubkey>,

            blacklister: Option<Pubkey>,

            seizer: Option<Pubkey>,

            transfer_hook_program_id: Option<Pubkey>,

            bump: u8,
        ) -> Self {
            Self {
                master_authority,

                pending_authority,

                mint,

                name,

                symbol,

                uri,

                decimals,

                compliance_enabled,

                permanent_delegate_enabled,

                transfer_hook_enabled,

                default_account_frozen,

                paused,

                total_minted,

                total_burned,

                pauser,

                freezer,

                burner,

                blacklister,

                seizer,

                transfer_hook_program_id,

                bump,
            }
        }
    }

    /// Custom struct: TokensBurned
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct TokensBurned {
        pub mint: Pubkey,

        pub from: Pubkey,

        pub amount: u64,

        pub burner: Pubkey,

        pub total_supply: u64,

        pub timestamp: i64,
    }

    impl TokensBurned {
        pub fn new(
            mint: Pubkey,

            from: Pubkey,

            amount: u64,

            burner: Pubkey,

            total_supply: u64,

            timestamp: i64,
        ) -> Self {
            Self {
                mint,

                from,

                amount,

                burner,

                total_supply,

                timestamp,
            }
        }
    }

    /// Custom struct: TokensMinted
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct TokensMinted {
        pub mint: Pubkey,

        pub recipient: Pubkey,

        pub amount: u64,

        pub minter: Pubkey,

        pub total_supply: u64,

        pub timestamp: i64,
    }

    impl TokensMinted {
        pub fn new(
            mint: Pubkey,

            recipient: Pubkey,

            amount: u64,

            minter: Pubkey,

            total_supply: u64,

            timestamp: i64,
        ) -> Self {
            Self {
                mint,

                recipient,

                amount,

                minter,

                total_supply,

                timestamp,
            }
        }
    }

    /// Custom struct: TokensSeized
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone, PartialEq)]
    pub struct TokensSeized {
        pub mint: Pubkey,

        pub from: Pubkey,

        pub to: Pubkey,

        pub amount: u64,

        pub seizer: Pubkey,

        pub timestamp: i64,
    }

    impl TokensSeized {
        pub fn new(
            mint: Pubkey,

            from: Pubkey,

            to: Pubkey,

            amount: u64,

            seizer: Pubkey,

            timestamp: i64,
        ) -> Self {
            Self {
                mint,

                from,

                to,

                amount,

                seizer,

                timestamp,
            }
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
