/**
 * SSS Devnet Smoke Test
 *
 * Exercises all major SSS operations against Solana devnet and records
 * transaction signatures. Results are written to DEVNET_EVIDENCE.md.
 *
 * Usage:
 *   ANCHOR_WALLET=~/.config/solana/id.json \
 *   ANCHOR_PROVIDER_URL=https://api.devnet.solana.com \
 *   npx ts-node scripts/devnet-smoke-test.ts
 */

import * as anchor from "@coral-xyz/anchor";
import {
  Connection,
  Keypair,
  PublicKey,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  getOrCreateAssociatedTokenAccount,
  TOKEN_2022_PROGRAM_ID,
  transferCheckedWithTransferHook,
} from "@solana/spl-token";
import BN from "bn.js";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

import { SolanaStablecoin } from "../sdk/src/core/stablecoin";
import { Preset, Role } from "../sdk/src/utils/types";
import { SSS_TRANSFER_HOOK_PROGRAM_ID } from "../sdk/src/utils/pda";

// ── Constants ────────────────────────────────────────────────────────────────
const EXPLORER_BASE = "https://explorer.solana.com/tx";
const DEVNET_EVIDENCE_PATH = path.resolve(__dirname, "../DEVNET_EVIDENCE.md");
const IDL_PATH = path.resolve(__dirname, "../target/idl/sss_core.json");

// ── Types ────────────────────────────────────────────────────────────────────
interface OperationResult {
  operation: string;
  signature: string | null;
  error: string | null;
  explorerUrl: string | null;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function explorerUrl(sig: string): string {
  return `${EXPLORER_BASE}/${sig}?cluster=devnet`;
}

function loadWallet(walletPath: string): Keypair {
  const resolved = walletPath.replace("~", os.homedir());
  const raw = fs.readFileSync(resolved, "utf-8");
  const secretKey = Uint8Array.from(JSON.parse(raw));
  return Keypair.fromSecretKey(secretKey);
}

async function run(
  label: string,
  fn: () => Promise<string>,
  results: OperationResult[]
): Promise<string | null> {
  process.stdout.write(`  [RUN]  ${label} ... `);
  try {
    const sig = await fn();
    process.stdout.write(`OK\n         sig: ${sig}\n`);
    results.push({
      operation: label,
      signature: sig,
      error: null,
      explorerUrl: explorerUrl(sig),
    });
    return sig;
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    process.stdout.write(`FAILED\n         err: ${msg}\n`);
    results.push({
      operation: label,
      signature: null,
      error: msg,
      explorerUrl: null,
    });
    return null;
  }
}

function renderTable(results: OperationResult[]): string {
  const rows = results.map((r, i) => {
    const n = String(i + 1).padStart(2, " ");
    const op = r.operation.padEnd(40, " ");
    const sig = r.signature ? r.signature.slice(0, 20) + "..." : "FAILED";
    const url = r.explorerUrl ?? r.error ?? "";
    return `| ${n} | ${op} | ${sig} | ${url} |`;
  });

  const header = [
    `| #  | Operation                                | Signature (truncated)    | Explorer / Error |`,
    `|----|------------------------------------------|--------------------------|------------------|`,
  ];

  return [...header, ...rows].join("\n");
}

function writeEvidence(
  results: OperationResult[],
  mint1: PublicKey | null,
  mint2: PublicKey | null,
  runDate: string
): void {
  const passed = results.filter((r) => r.signature !== null).length;
  const failed = results.filter((r) => r.signature === null).length;

  const fullSigSection = results
    .map((r, i) => {
      const n = String(i + 1).padStart(2, " ");
      if (r.signature) {
        return (
          `### ${n}. ${r.operation}\n` +
          `- **Signature**: \`${r.signature}\`\n` +
          `- **Explorer**: [View on Solana Explorer](${r.explorerUrl})\n`
        );
      } else {
        return (
          `### ${n}. ${r.operation}\n` +
          `- **Status**: FAILED\n` +
          `- **Error**: \`${r.error}\`\n`
        );
      }
    })
    .join("\n");

  const content = `# SSS Devnet Evidence

> Auto-generated by \`scripts/devnet-smoke-test.ts\` on **${runDate}**

## Summary

| Metric | Value |
|--------|-------|
| Run date | ${runDate} |
| Network | Devnet |
| SSS-1 mint | ${mint1 ? mint1.toBase58() : "not created"} |
| SSS-2 mint | ${mint2 ? mint2.toBase58() : "not created"} |
| Operations passed | ${passed} / ${results.length} |
| Operations failed | ${failed} / ${results.length} |

## Operations Table

${renderTable(results)}

## Full Transaction Details

${fullSigSection}

---

*Program IDs used:*
- \`sss_core\`: \`GmG49Q2d988k5C6dkTLLCihGfH5G6QVg5Rbgv54Z7iw4\`
- \`sss_transfer_hook\`: \`2b5HCPo4PC7w63MmUnXxuR9kwtaQpni8AXktfZHiMf2p\`
`;

  fs.writeFileSync(DEVNET_EVIDENCE_PATH, content, "utf-8");
  console.log(`\nEvidence written to: ${DEVNET_EVIDENCE_PATH}`);
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log("=== SSS Devnet Smoke Test ===\n");

  // ── Provider setup ─────────────────────────────────────────────────────────
  const walletPath =
    process.env.ANCHOR_WALLET ?? "~/.config/solana/id.json";
  const rpcUrl =
    process.env.ANCHOR_PROVIDER_URL ?? "https://api.devnet.solana.com";

  const adminKeypair = loadWallet(walletPath);
  const connection = new Connection(rpcUrl, "confirmed");
  const wallet = new anchor.Wallet(adminKeypair);
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
    preflightCommitment: "confirmed",
  });
  anchor.setProvider(provider);

  console.log(`Wallet : ${adminKeypair.publicKey.toBase58()}`);
  console.log(`RPC    : ${rpcUrl}\n`);

  // Check balance
  const balance = await connection.getBalance(adminKeypair.publicKey);
  console.log(`Balance: ${(balance / LAMPORTS_PER_SOL).toFixed(4)} SOL\n`);
  if (balance < 0.1 * LAMPORTS_PER_SOL) {
    console.warn(
      "WARNING: Low balance. Run `solana airdrop 2` on devnet before continuing.\n"
    );
  }

  // ── Load IDL and SDK ───────────────────────────────────────────────────────
  const idlRaw = fs.readFileSync(IDL_PATH, "utf-8");
  const idl = JSON.parse(idlRaw);

  const sdk = new SolanaStablecoin(provider, idl);

  const results: OperationResult[] = [];
  const runDate = new Date().toISOString();

  let mint1: PublicKey | null = null;
  let mint2: PublicKey | null = null;
  let adminAta1: PublicKey | null = null;

  // ── (a) Create SSS-1 mint ─────────────────────────────────────────────────
  console.log("--- SSS-1 Operations ---\n");

  {
    let mint1Pubkey: PublicKey | null = null;
    await run(
      "Create SSS-1 mint (basic, no transfer hook)",
      async () => {
        const result = await sdk.createMint({
          name: "Test SSS-1 Stablecoin",
          symbol: "TSSS1",
          uri: "https://example.com/tsss1.json",
          decimals: 6,
          preset: Preset.SSS1,
        });
        mint1Pubkey = result.mint;
        mint1 = result.mint;
        return result.signature;
      },
      results
    );
    if (mint1Pubkey) {
      console.log(`  SSS-1 mint: ${(mint1Pubkey as PublicKey).toBase58()}\n`);
    }
  }

  // ── (b) Grant Minter role (self-grant) ────────────────────────────────────
  if (mint1) {
    await run(
      "Grant Minter role to admin (self-grant)",
      () =>
        sdk.grantRole({
          mint: mint1!,
          holder: adminKeypair.publicKey,
          role: Role.Minter,
          allowance: new BN(1_000_000_000), // 1000 tokens at 6 decimals
        }),
      results
    );
  } else {
    results.push({
      operation: "Grant Minter role to admin (self-grant)",
      signature: null,
      error: "Skipped: SSS-1 mint not created",
      explorerUrl: null,
    });
  }

  // ── (c) Grant Burner role (self-grant, needed for burn_from) ──────────────
  if (mint1) {
    await run(
      "Grant Burner role to admin (self-grant)",
      () =>
        sdk.grantRole({
          mint: mint1!,
          holder: adminKeypair.publicKey,
          role: Role.Burner,
          allowance: new BN(1_000_000_000),
        }),
      results
    );
  } else {
    results.push({
      operation: "Grant Burner role to admin (self-grant)",
      signature: null,
      error: "Skipped: SSS-1 mint not created",
      explorerUrl: null,
    });
  }

  // ── Create ATA for minting ─────────────────────────────────────────────────
  if (mint1) {
    try {
      console.log("  Creating associated token account for admin...");
      const ataInfo = await getOrCreateAssociatedTokenAccount(
        connection,
        adminKeypair,
        mint1,
        adminKeypair.publicKey,
        false,
        "confirmed",
        { commitment: "confirmed" },
        TOKEN_2022_PROGRAM_ID
      );
      adminAta1 = ataInfo.address;
      console.log(`  ATA: ${adminAta1.toBase58()}\n`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  Failed to create ATA: ${msg}\n`);
    }
  }

  // ── (d) mint_to 1000 tokens ───────────────────────────────────────────────
  if (mint1 && adminAta1) {
    await run(
      "mint_to 1000 tokens",
      () =>
        sdk.mintTo({
          mint: mint1!,
          to: adminAta1!,
          amount: new BN(1_000 * 1_000_000), // 1000 tokens at 6 decimals
        }),
      results
    );
  } else {
    results.push({
      operation: "mint_to 1000 tokens",
      signature: null,
      error: "Skipped: mint or ATA not available",
      explorerUrl: null,
    });
  }

  // ── (f) pause ────────────────────────────────────────────────────────────
  if (mint1) {
    await run(
      "pause",
      () => sdk.pause(mint1!),
      results
    );
  } else {
    results.push({
      operation: "pause",
      signature: null,
      error: "Skipped: SSS-1 mint not created",
      explorerUrl: null,
    });
  }

  // ── (g) unpause ───────────────────────────────────────────────────────────
  if (mint1) {
    await run(
      "unpause",
      () => sdk.unpause(mint1!),
      results
    );
  } else {
    results.push({
      operation: "unpause",
      signature: null,
      error: "Skipped: SSS-1 mint not created",
      explorerUrl: null,
    });
  }

  // ── (h) transfer_admin to a new keypair ───────────────────────────────────
  const newAdminKeypair = Keypair.generate();
  console.log(`  New admin pubkey: ${newAdminKeypair.publicKey.toBase58()}`);

  if (mint1) {
    await run(
      "transfer_admin to new keypair",
      () => sdk.transferAdmin(mint1!, newAdminKeypair.publicKey),
      results
    );
  } else {
    results.push({
      operation: "transfer_admin to new keypair",
      signature: null,
      error: "Skipped: SSS-1 mint not created",
      explorerUrl: null,
    });
  }

  // ── (i) accept_admin from the new keypair ─────────────────────────────────
  // Switch provider wallet to the new admin keypair to call accept_admin
  if (mint1) {
    // Fund new admin with a small SOL transfer so it can pay fees
    try {
      const transferIx = anchor.web3.SystemProgram.transfer({
        fromPubkey: adminKeypair.publicKey,
        toPubkey: newAdminKeypair.publicKey,
        lamports: 0.05 * LAMPORTS_PER_SOL,
      });
      const transferTx = new anchor.web3.Transaction().add(transferIx);
      const transferSig = await provider.sendAndConfirm(transferTx);
      console.log(`  Transferred 0.05 SOL to new admin (${transferSig})\n`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`  SOL transfer to new admin failed (continuing): ${msg}\n`);
    }

    const newAdminWallet = new anchor.Wallet(newAdminKeypair);
    const newAdminProvider = new anchor.AnchorProvider(
      connection,
      newAdminWallet,
      { commitment: "confirmed", preflightCommitment: "confirmed" }
    );
    const newAdminSdk = new SolanaStablecoin(newAdminProvider, idl);

    await run(
      "accept_admin from new keypair",
      () => newAdminSdk.acceptAdmin(mint1!),
      results
    );

    // Transfer admin back to original admin so remaining operations work
    await run(
      "transfer_admin back to original admin",
      () => newAdminSdk.transferAdmin(mint1!, adminKeypair.publicKey),
      results
    );

    await run(
      "accept_admin back (original admin reclaims)",
      () => sdk.acceptAdmin(mint1!),
      results
    );
  } else {
    results.push(
      {
        operation: "accept_admin from new keypair",
        signature: null,
        error: "Skipped: SSS-1 mint not created",
        explorerUrl: null,
      },
      {
        operation: "transfer_admin back to original admin",
        signature: null,
        error: "Skipped: SSS-1 mint not created",
        explorerUrl: null,
      },
      {
        operation: "accept_admin back (original admin reclaims)",
        signature: null,
        error: "Skipped: SSS-1 mint not created",
        explorerUrl: null,
      }
    );
  }

  // ── SSS-2 Operations ───────────────────────────────────────────────────────
  console.log("\n--- SSS-2 Operations ---\n");

  // ── (j) Create SSS-2 mint (with transfer hook) ────────────────────────────
  {
    let mint2Pubkey: PublicKey | null = null;
    await run(
      "Create SSS-2 mint (with transfer hook)",
      async () => {
        const result = await sdk.createMint({
          name: "Test SSS-2 Stablecoin",
          symbol: "TSSS2",
          uri: "https://example.com/tsss2.json",
          decimals: 6,
          preset: Preset.SSS2,
          transferHookProgram: SSS_TRANSFER_HOOK_PROGRAM_ID,
          treasury: adminKeypair.publicKey,
        });
        mint2Pubkey = result.mint;
        mint2 = result.mint;
        return result.signature;
      },
      results
    );
    if (mint2Pubkey) {
      console.log(`  SSS-2 mint: ${(mint2Pubkey as PublicKey).toBase58()}\n`);
    }
  }

  // ── (k) Initialize hook for SSS-2 ────────────────────────────────────────
  if (mint2) {
    await run(
      "initialize_hook for SSS-2",
      () => sdk.initializeHook(mint2!),
      results
    );
  } else {
    results.push({
      operation: "initialize_hook for SSS-2",
      signature: null,
      error: "Skipped: SSS-2 mint not created",
      explorerUrl: null,
    });
  }

  // ── SSS-2: Grant Minter+Burner, mint, then burn_from ─────────────────────
  if (mint2) {
    await run(
      "Grant Minter role for SSS-2",
      () =>
        sdk.grantRole({
          mint: mint2!,
          holder: adminKeypair.publicKey,
          role: Role.Minter,
          allowance: new BN(10_000 * 1_000_000),
        }),
      results
    );

    await run(
      "Grant Burner role for SSS-2",
      () =>
        sdk.grantRole({
          mint: mint2!,
          holder: adminKeypair.publicKey,
          role: Role.Burner,
          allowance: new BN(0),
        }),
      results
    );

    // Create ATA + mint tokens for SSS-2 so we can burn
    try {
      const ata2Info = await getOrCreateAssociatedTokenAccount(
        connection,
        adminKeypair,
        mint2!,
        adminKeypair.publicKey,
        false,
        "confirmed",
        { commitment: "confirmed" },
        TOKEN_2022_PROGRAM_ID
      );
      const adminAta2 = ata2Info.address;
      console.log(`  SSS-2 ATA: ${adminAta2.toBase58()}`);

      await run(
        "mint_to 500 tokens (SSS-2)",
        () =>
          sdk.mintTo({
            mint: mint2!,
            to: adminAta2,
            amount: new BN(500 * 1_000_000),
          }),
        results
      );

      await run(
        "burn_from 50 tokens (SSS-2)",
        () =>
          sdk.burnFrom({
            mint: mint2!,
            from: adminAta2,
            amount: new BN(50 * 1_000_000),
          }),
        results
      );
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  SSS-2 ATA/mint/burn setup failed: ${msg}`);
    }
  }

  // ── (l) Grant ComplianceOfficer role ─────────────────────────────────────
  if (mint2) {
    await run(
      "Grant ComplianceOfficer role to admin",
      () =>
        sdk.grantRole({
          mint: mint2!,
          holder: adminKeypair.publicKey,
          role: Role.ComplianceOfficer,
          allowance: new BN(0), // ComplianceOfficer has no allowance concept
        }),
      results
    );
  } else {
    results.push({
      operation: "Grant ComplianceOfficer role to admin",
      signature: null,
      error: "Skipped: SSS-2 mint not created",
      explorerUrl: null,
    });
  }

  // ── (m) Blacklist a random wallet ─────────────────────────────────────────
  const randomWallet = Keypair.generate().publicKey;
  console.log(`  Random wallet to blacklist: ${randomWallet.toBase58()}`);

  if (mint2) {
    await run(
      "blacklist random wallet",
      () =>
        sdk.blacklist({
          mint: mint2!,
          wallet: randomWallet,
        }),
      results
    );
  } else {
    results.push({
      operation: "blacklist random wallet",
      signature: null,
      error: "Skipped: SSS-2 mint not created",
      explorerUrl: null,
    });
  }

  // ── (n) Unblacklist that wallet ───────────────────────────────────────────
  if (mint2) {
    await run(
      "unblacklist random wallet",
      () =>
        sdk.unblacklist({
          mint: mint2!,
          wallet: randomWallet,
        }),
      results
    );
  } else {
    results.push({
      operation: "unblacklist random wallet",
      signature: null,
      error: "Skipped: SSS-2 mint not created",
      explorerUrl: null,
    });
  }

  // ── SSS-2 compliance operations: thaw/freeze/seize/transfer-with-hook ─────
  //
  // For these operations we need:
  //   - a user keypair whose ATA starts frozen (DefaultAccountState on SSS-2)
  //   - a treasury ATA to receive seized tokens
  //   - a second user keypair for the transfer-with-hook test
  //   - Seizer role granted to admin
  //
  // We reuse the adminAta2 that was minted earlier for the burn test. The
  // admin also acts as the compliance officer (admin path) for thaw/freeze.

  let userKeypair2: Keypair | null = null;
  let userAta2: PublicKey | null = null;
  let treasuryAta2: PublicKey | null = null;

  if (mint2) {
    // Create a fresh user keypair and fund it so it can pay ATA creation fees
    userKeypair2 = Keypair.generate();
    console.log(`  SSS-2 user keypair: ${userKeypair2.publicKey.toBase58()}`);

    try {
      const fundIx = anchor.web3.SystemProgram.transfer({
        fromPubkey: adminKeypair.publicKey,
        toPubkey: userKeypair2.publicKey,
        lamports: 0.05 * LAMPORTS_PER_SOL,
      });
      const fundTx = new anchor.web3.Transaction().add(fundIx);
      await provider.sendAndConfirm(fundTx);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`  Failed to fund user keypair (continuing): ${msg}`);
    }

    // Create the user's ATA — it starts frozen due to DefaultAccountState
    try {
      const ataInfo = await getOrCreateAssociatedTokenAccount(
        connection,
        adminKeypair,
        mint2,
        userKeypair2.publicKey,
        false,
        "confirmed",
        { commitment: "confirmed" },
        TOKEN_2022_PROGRAM_ID
      );
      userAta2 = ataInfo.address;
      console.log(`  SSS-2 user ATA: ${userAta2.toBase58()}`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  Failed to create user ATA: ${msg}`);
    }

    // Create treasury ATA (admin is the treasury in this smoke test)
    try {
      const treaInfo = await getOrCreateAssociatedTokenAccount(
        connection,
        adminKeypair,
        mint2,
        adminKeypair.publicKey,
        false,
        "confirmed",
        { commitment: "confirmed" },
        TOKEN_2022_PROGRAM_ID
      );
      // adminAta2 was already created above; getOrCreate returns existing one
      treasuryAta2 = treaInfo.address;
      console.log(`  SSS-2 treasury ATA: ${treasuryAta2.toBase58()}\n`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  Failed to get treasury ATA: ${msg}`);
    }
  }

  // ── (o) thaw_account — thaw the user's frozen ATA ────────────────────────
  if (mint2 && userAta2) {
    await run(
      "thaw_account (user ATA, admin path)",
      () => sdk.thawAccount(mint2!, userAta2!),
      results
    );
  } else {
    results.push({
      operation: "thaw_account (user ATA, admin path)",
      signature: null,
      error: "Skipped: SSS-2 mint or user ATA not available",
      explorerUrl: null,
    });
  }

  // Mint tokens to the user ATA now that it is thawed
  if (mint2 && userAta2) {
    try {
      await run(
        "mint_to 100 tokens to user ATA (SSS-2)",
        () =>
          sdk.mintTo({
            mint: mint2!,
            to: userAta2!,
            amount: new BN(100 * 1_000_000),
          }),
        results
      );
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  mint_to user ATA failed (continuing): ${msg}`);
    }
  } else {
    results.push({
      operation: "mint_to 100 tokens to user ATA (SSS-2)",
      signature: null,
      error: "Skipped: SSS-2 mint or user ATA not available",
      explorerUrl: null,
    });
  }

  // ── (p) freeze_account — freeze the user's ATA back ──────────────────────
  if (mint2 && userAta2) {
    await run(
      "freeze_account (user ATA, admin path)",
      () => sdk.freezeAccount(mint2!, userAta2!),
      results
    );
  } else {
    results.push({
      operation: "freeze_account (user ATA, admin path)",
      signature: null,
      error: "Skipped: SSS-2 mint or user ATA not available",
      explorerUrl: null,
    });
  }

  // ── (q) thaw again — re-thaw so we can do the seize flow ─────────────────
  if (mint2 && userAta2) {
    await run(
      "thaw_account again (pre-seize, admin path)",
      () => sdk.thawAccount(mint2!, userAta2!),
      results
    );
  } else {
    results.push({
      operation: "thaw_account again (pre-seize, admin path)",
      signature: null,
      error: "Skipped: SSS-2 mint or user ATA not available",
      explorerUrl: null,
    });
  }

  // ── (r) seize — blacklist user, then seize tokens to treasury ────────────
  //
  // seize() requires:
  //   - a Seizer role granted to admin
  //   - user blacklisted
  //   - from: user ATA (frozen by program during seize)
  //   - treasuryAta: destination ATA
  //
  // We grant Seizer role to admin, blacklist the user, then call seize.

  if (mint2 && userAta2 && treasuryAta2 && userKeypair2) {
    // Grant Seizer role to admin
    await run(
      "Grant Seizer role to admin (SSS-2)",
      () =>
        sdk.grantRole({
          mint: mint2!,
          holder: adminKeypair.publicKey,
          role: Role.Seizer,
          allowance: new BN(0),
        }),
      results
    );

    // Blacklist the user wallet
    await run(
      "blacklist user wallet (pre-seize)",
      () =>
        sdk.blacklist({
          mint: mint2!,
          wallet: userKeypair2!.publicKey,
        }),
      results
    );

    // seize tokens from user ATA to treasury ATA
    await run(
      "seize 100 tokens from user ATA to treasury",
      () =>
        sdk.seize({
          mint: mint2!,
          from: userAta2!,
          treasuryAta: treasuryAta2!,
          amount: new BN(100 * 1_000_000),
        }),
      results
    );
  } else {
    results.push(
      {
        operation: "Grant Seizer role to admin (SSS-2)",
        signature: null,
        error: "Skipped: SSS-2 mint, user ATA, or treasury ATA not available",
        explorerUrl: null,
      },
      {
        operation: "blacklist user wallet (pre-seize)",
        signature: null,
        error: "Skipped: SSS-2 mint, user ATA, or treasury ATA not available",
        explorerUrl: null,
      },
      {
        operation: "seize 100 tokens from user ATA to treasury",
        signature: null,
        error: "Skipped: SSS-2 mint, user ATA, or treasury ATA not available",
        explorerUrl: null,
      }
    );
  }

  // ── (s) token transfer with hook ──────────────────────────────────────────
  //
  // Proves the transfer hook executes on a regular transferChecked.
  // Flow:
  //   1. Create a second user keypair (user2)
  //   2. Create user2's ATA (starts frozen — DefaultAccountState)
  //   3. Thaw user2's ATA so it can receive tokens
  //   4. Mint fresh tokens to the admin ATA (adminAta2 / treasuryAta2)
  //   5. Transfer tokens from admin ATA to user2 ATA via transferCheckedWithTransferHook

  let user2Keypair: Keypair | null = null;
  let user2Ata: PublicKey | null = null;

  if (mint2) {
    user2Keypair = Keypair.generate();
    console.log(`  SSS-2 user2 keypair: ${user2Keypair.publicKey.toBase58()}`);

    try {
      const fundIx = anchor.web3.SystemProgram.transfer({
        fromPubkey: adminKeypair.publicKey,
        toPubkey: user2Keypair.publicKey,
        lamports: 0.05 * LAMPORTS_PER_SOL,
      });
      const fundTx = new anchor.web3.Transaction().add(fundIx);
      await provider.sendAndConfirm(fundTx);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`  Failed to fund user2 keypair (continuing): ${msg}`);
    }

    // Create user2's ATA
    try {
      const ata2Info = await getOrCreateAssociatedTokenAccount(
        connection,
        adminKeypair,
        mint2,
        user2Keypair.publicKey,
        false,
        "confirmed",
        { commitment: "confirmed" },
        TOKEN_2022_PROGRAM_ID
      );
      user2Ata = ata2Info.address;
      console.log(`  SSS-2 user2 ATA: ${user2Ata.toBase58()}`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  Failed to create user2 ATA: ${msg}`);
    }

    // Thaw user2's ATA so it can receive tokens
    if (user2Ata) {
      await run(
        "thaw_account user2 ATA (pre-transfer-hook test)",
        () => sdk.thawAccount(mint2!, user2Ata!),
        results
      );
    } else {
      results.push({
        operation: "thaw_account user2 ATA (pre-transfer-hook test)",
        signature: null,
        error: "Skipped: user2 ATA not created",
        explorerUrl: null,
      });
    }
  } else {
    results.push({
      operation: "thaw_account user2 ATA (pre-transfer-hook test)",
      signature: null,
      error: "Skipped: SSS-2 mint not created",
      explorerUrl: null,
    });
  }

  // Transfer tokens from admin (source) to user2 (destination) via hook
  if (mint2 && treasuryAta2 && user2Ata) {
    await run(
      "transferChecked with transfer hook (admin -> user2)",
      async () => {
        return transferCheckedWithTransferHook(
          connection,
          adminKeypair,          // payer
          treasuryAta2!,         // source (admin ATA, which holds seized/minted tokens)
          mint2!,                // mint
          user2Ata!,             // destination
          adminKeypair,          // authority (owner of source ATA)
          BigInt(10 * 1_000_000), // amount: 10 tokens at 6 decimals
          6,                     // decimals
          [],                    // no multisigners
          { commitment: "confirmed" },
          TOKEN_2022_PROGRAM_ID
        );
      },
      results
    );
  } else {
    results.push({
      operation: "transferChecked with transfer hook (admin -> user2)",
      signature: null,
      error: "Skipped: SSS-2 mint, source ATA, or destination ATA not available",
      explorerUrl: null,
    });
  }

  // ── Summary Table ─────────────────────────────────────────────────────────
  console.log("\n=== Results Summary ===\n");
  console.log(renderTable(results));

  const passed = results.filter((r) => r.signature !== null).length;
  const failed = results.filter((r) => r.signature === null).length;
  console.log(`\n${passed}/${results.length} operations succeeded, ${failed} failed.\n`);

  // ── Write Evidence ─────────────────────────────────────────────────────────
  writeEvidence(results, mint1, mint2, runDate);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
