//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct StablecoinDecoder;
pub const PROGRAM_ID: Pubkey = solana_pubkey::Pubkey::from_str_const("Gbq8ZoZ4fE2J8wywFDYgSREPWL5qhtaneAX9PwQuQyCC");

pub mod compatibility;
pub mod accounts;
pub mod instructions;
pub mod types;
pub mod events;
