//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct StablecoinDecoder;
pub const PROGRAM_ID: Pubkey = solana_pubkey::Pubkey::from_str_const("C7k7FTRLGLB5FJS7hWrpjqRiwmj5Px9DzMQUeouAxJ9r");

pub mod compatibility;
pub mod accounts;
pub mod instructions;
pub mod types;
pub mod events;
