/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithRpc,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type GetAccountInfoApi,
  type GetMultipleAccountsApi,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfFetchFunctions,
  addSelfPlanAndSendFunctions,
  type SelfFetchFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/program-client-core";
import {
  getBlacklistEntryCodec,
  getMinterQuotaCodec,
  getRoleConfigCodec,
  getStablecoinConfigCodec,
  type BlacklistEntry,
  type BlacklistEntryArgs,
  type MinterQuota,
  type MinterQuotaArgs,
  type RoleConfig,
  type RoleConfigArgs,
  type StablecoinConfig,
  type StablecoinConfigArgs,
} from "../accounts";
import {
  getAddToBlacklistInstructionAsync,
  getBurnInstructionAsync,
  getFreezeAccountInstructionAsync,
  getInitializeInstructionAsync,
  getMintInstructionAsync,
  getPauseInstructionAsync,
  getRemoveFromBlacklistInstructionAsync,
  getSeizeInstructionAsync,
  getThawAccountInstructionAsync,
  getTransferAuthorityInstructionAsync,
  getUnpauseInstructionAsync,
  getUpdateMinterInstructionAsync,
  getUpdateRolesInstructionAsync,
  parseAddToBlacklistInstruction,
  parseBurnInstruction,
  parseFreezeAccountInstruction,
  parseInitializeInstruction,
  parseMintInstruction,
  parsePauseInstruction,
  parseRemoveFromBlacklistInstruction,
  parseSeizeInstruction,
  parseThawAccountInstruction,
  parseTransferAuthorityInstruction,
  parseUnpauseInstruction,
  parseUpdateMinterInstruction,
  parseUpdateRolesInstruction,
  type AddToBlacklistAsyncInput,
  type BurnAsyncInput,
  type FreezeAccountAsyncInput,
  type InitializeAsyncInput,
  type MintAsyncInput,
  type ParsedAddToBlacklistInstruction,
  type ParsedBurnInstruction,
  type ParsedFreezeAccountInstruction,
  type ParsedInitializeInstruction,
  type ParsedMintInstruction,
  type ParsedPauseInstruction,
  type ParsedRemoveFromBlacklistInstruction,
  type ParsedSeizeInstruction,
  type ParsedThawAccountInstruction,
  type ParsedTransferAuthorityInstruction,
  type ParsedUnpauseInstruction,
  type ParsedUpdateMinterInstruction,
  type ParsedUpdateRolesInstruction,
  type PauseAsyncInput,
  type RemoveFromBlacklistAsyncInput,
  type SeizeAsyncInput,
  type ThawAccountAsyncInput,
  type TransferAuthorityAsyncInput,
  type UnpauseAsyncInput,
  type UpdateMinterAsyncInput,
  type UpdateRolesAsyncInput,
} from "../instructions";

export const STABLECOIN_PROGRAM_ADDRESS =
  "Gbq8ZoZ4fE2J8wywFDYgSREPWL5qhtaneAX9PwQuQyCC" as Address<"Gbq8ZoZ4fE2J8wywFDYgSREPWL5qhtaneAX9PwQuQyCC">;

export enum StablecoinAccount {
  BlacklistEntry,
  MinterQuota,
  RoleConfig,
  StablecoinConfig,
}

export function identifyStablecoinAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): StablecoinAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([218, 179, 231, 40, 141, 25, 168, 189]),
      ),
      0,
    )
  ) {
    return StablecoinAccount.BlacklistEntry;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([42, 21, 27, 217, 49, 82, 230, 89]),
      ),
      0,
    )
  ) {
    return StablecoinAccount.MinterQuota;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([60, 138, 76, 113, 196, 104, 162, 73]),
      ),
      0,
    )
  ) {
    return StablecoinAccount.RoleConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([127, 25, 244, 213, 1, 192, 101, 6]),
      ),
      0,
    )
  ) {
    return StablecoinAccount.StablecoinConfig;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    { accountData: data, programName: "stablecoin" },
  );
}

export enum StablecoinInstruction {
  AddToBlacklist,
  Burn,
  FreezeAccount,
  Initialize,
  Mint,
  Pause,
  RemoveFromBlacklist,
  Seize,
  ThawAccount,
  TransferAuthority,
  Unpause,
  UpdateMinter,
  UpdateRoles,
}

export function identifyStablecoinInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): StablecoinInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([90, 115, 98, 231, 173, 119, 117, 176]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.AddToBlacklist;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([116, 110, 29, 56, 107, 219, 42, 93]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.Burn;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([253, 75, 82, 133, 167, 238, 43, 130]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.FreezeAccount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([51, 57, 225, 47, 182, 146, 137, 166]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.Mint;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([211, 22, 221, 251, 74, 121, 193, 47]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.Pause;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([47, 105, 20, 10, 165, 168, 203, 219]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.RemoveFromBlacklist;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([129, 159, 143, 31, 161, 224, 241, 84]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.Seize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([115, 152, 79, 213, 213, 169, 184, 35]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.ThawAccount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([48, 169, 76, 72, 229, 180, 55, 161]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.TransferAuthority;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([169, 144, 4, 38, 10, 141, 188, 255]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.Unpause;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([164, 129, 164, 88, 75, 29, 91, 38]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.UpdateMinter;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([220, 152, 205, 233, 177, 123, 219, 125]),
      ),
      0,
    )
  ) {
    return StablecoinInstruction.UpdateRoles;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "stablecoin" },
  );
}

export type ParsedStablecoinInstruction<
  TProgram extends string = "Gbq8ZoZ4fE2J8wywFDYgSREPWL5qhtaneAX9PwQuQyCC",
> =
  | ({
      instructionType: StablecoinInstruction.AddToBlacklist;
    } & ParsedAddToBlacklistInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.Burn;
    } & ParsedBurnInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.FreezeAccount;
    } & ParsedFreezeAccountInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.Mint;
    } & ParsedMintInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.Pause;
    } & ParsedPauseInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.RemoveFromBlacklist;
    } & ParsedRemoveFromBlacklistInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.Seize;
    } & ParsedSeizeInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.ThawAccount;
    } & ParsedThawAccountInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.TransferAuthority;
    } & ParsedTransferAuthorityInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.Unpause;
    } & ParsedUnpauseInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.UpdateMinter;
    } & ParsedUpdateMinterInstruction<TProgram>)
  | ({
      instructionType: StablecoinInstruction.UpdateRoles;
    } & ParsedUpdateRolesInstruction<TProgram>);

export function parseStablecoinInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedStablecoinInstruction<TProgram> {
  const instructionType = identifyStablecoinInstruction(instruction);
  switch (instructionType) {
    case StablecoinInstruction.AddToBlacklist: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.AddToBlacklist,
        ...parseAddToBlacklistInstruction(instruction),
      };
    }
    case StablecoinInstruction.Burn: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.Burn,
        ...parseBurnInstruction(instruction),
      };
    }
    case StablecoinInstruction.FreezeAccount: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.FreezeAccount,
        ...parseFreezeAccountInstruction(instruction),
      };
    }
    case StablecoinInstruction.Initialize: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.Initialize,
        ...parseInitializeInstruction(instruction),
      };
    }
    case StablecoinInstruction.Mint: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.Mint,
        ...parseMintInstruction(instruction),
      };
    }
    case StablecoinInstruction.Pause: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.Pause,
        ...parsePauseInstruction(instruction),
      };
    }
    case StablecoinInstruction.RemoveFromBlacklist: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.RemoveFromBlacklist,
        ...parseRemoveFromBlacklistInstruction(instruction),
      };
    }
    case StablecoinInstruction.Seize: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.Seize,
        ...parseSeizeInstruction(instruction),
      };
    }
    case StablecoinInstruction.ThawAccount: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.ThawAccount,
        ...parseThawAccountInstruction(instruction),
      };
    }
    case StablecoinInstruction.TransferAuthority: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.TransferAuthority,
        ...parseTransferAuthorityInstruction(instruction),
      };
    }
    case StablecoinInstruction.Unpause: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.Unpause,
        ...parseUnpauseInstruction(instruction),
      };
    }
    case StablecoinInstruction.UpdateMinter: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.UpdateMinter,
        ...parseUpdateMinterInstruction(instruction),
      };
    }
    case StablecoinInstruction.UpdateRoles: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StablecoinInstruction.UpdateRoles,
        ...parseUpdateRolesInstruction(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        {
          instructionType: instructionType as string,
          programName: "stablecoin",
        },
      );
  }
}

export type StablecoinPlugin = {
  accounts: StablecoinPluginAccounts;
  instructions: StablecoinPluginInstructions;
};

export type StablecoinPluginAccounts = {
  blacklistEntry: ReturnType<typeof getBlacklistEntryCodec> &
    SelfFetchFunctions<BlacklistEntryArgs, BlacklistEntry>;
  minterQuota: ReturnType<typeof getMinterQuotaCodec> &
    SelfFetchFunctions<MinterQuotaArgs, MinterQuota>;
  roleConfig: ReturnType<typeof getRoleConfigCodec> &
    SelfFetchFunctions<RoleConfigArgs, RoleConfig>;
  stablecoinConfig: ReturnType<typeof getStablecoinConfigCodec> &
    SelfFetchFunctions<StablecoinConfigArgs, StablecoinConfig>;
};

export type StablecoinPluginInstructions = {
  addToBlacklist: (
    input: AddToBlacklistAsyncInput,
  ) => ReturnType<typeof getAddToBlacklistInstructionAsync> &
    SelfPlanAndSendFunctions;
  burn: (
    input: BurnAsyncInput,
  ) => ReturnType<typeof getBurnInstructionAsync> & SelfPlanAndSendFunctions;
  freezeAccount: (
    input: FreezeAccountAsyncInput,
  ) => ReturnType<typeof getFreezeAccountInstructionAsync> &
    SelfPlanAndSendFunctions;
  initialize: (
    input: InitializeAsyncInput,
  ) => ReturnType<typeof getInitializeInstructionAsync> &
    SelfPlanAndSendFunctions;
  mint: (
    input: MintAsyncInput,
  ) => ReturnType<typeof getMintInstructionAsync> & SelfPlanAndSendFunctions;
  pause: (
    input: PauseAsyncInput,
  ) => ReturnType<typeof getPauseInstructionAsync> & SelfPlanAndSendFunctions;
  removeFromBlacklist: (
    input: RemoveFromBlacklistAsyncInput,
  ) => ReturnType<typeof getRemoveFromBlacklistInstructionAsync> &
    SelfPlanAndSendFunctions;
  seize: (
    input: SeizeAsyncInput,
  ) => ReturnType<typeof getSeizeInstructionAsync> & SelfPlanAndSendFunctions;
  thawAccount: (
    input: ThawAccountAsyncInput,
  ) => ReturnType<typeof getThawAccountInstructionAsync> &
    SelfPlanAndSendFunctions;
  transferAuthority: (
    input: TransferAuthorityAsyncInput,
  ) => ReturnType<typeof getTransferAuthorityInstructionAsync> &
    SelfPlanAndSendFunctions;
  unpause: (
    input: UnpauseAsyncInput,
  ) => ReturnType<typeof getUnpauseInstructionAsync> & SelfPlanAndSendFunctions;
  updateMinter: (
    input: UpdateMinterAsyncInput,
  ) => ReturnType<typeof getUpdateMinterInstructionAsync> &
    SelfPlanAndSendFunctions;
  updateRoles: (
    input: UpdateRolesAsyncInput,
  ) => ReturnType<typeof getUpdateRolesInstructionAsync> &
    SelfPlanAndSendFunctions;
};

export type StablecoinPluginRequirements = ClientWithRpc<
  GetAccountInfoApi & GetMultipleAccountsApi
> &
  ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function stablecoinProgram() {
  return <T extends StablecoinPluginRequirements>(client: T) => {
    return {
      ...client,
      stablecoin: <StablecoinPlugin>{
        accounts: {
          blacklistEntry: addSelfFetchFunctions(
            client,
            getBlacklistEntryCodec(),
          ),
          minterQuota: addSelfFetchFunctions(client, getMinterQuotaCodec()),
          roleConfig: addSelfFetchFunctions(client, getRoleConfigCodec()),
          stablecoinConfig: addSelfFetchFunctions(
            client,
            getStablecoinConfigCodec(),
          ),
        },
        instructions: {
          addToBlacklist: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAddToBlacklistInstructionAsync(input),
            ),
          burn: (input) =>
            addSelfPlanAndSendFunctions(client, getBurnInstructionAsync(input)),
          freezeAccount: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getFreezeAccountInstructionAsync(input),
            ),
          initialize: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializeInstructionAsync(input),
            ),
          mint: (input) =>
            addSelfPlanAndSendFunctions(client, getMintInstructionAsync(input)),
          pause: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getPauseInstructionAsync(input),
            ),
          removeFromBlacklist: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getRemoveFromBlacklistInstructionAsync(input),
            ),
          seize: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSeizeInstructionAsync(input),
            ),
          thawAccount: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getThawAccountInstructionAsync(input),
            ),
          transferAuthority: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getTransferAuthorityInstructionAsync(input),
            ),
          unpause: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUnpauseInstructionAsync(input),
            ),
          updateMinter: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateMinterInstructionAsync(input),
            ),
          updateRoles: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getUpdateRolesInstructionAsync(input),
            ),
        },
      },
    };
  };
}
