/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { STABLECOIN_PROGRAM_ADDRESS } from "../programs";

/** InvalidName: Invalid stablecoin name */
export const STABLECOIN_ERROR__INVALID_NAME = 0x1770; // 6000
/** InvalidSymbol: Invalid stablecoin symbol */
export const STABLECOIN_ERROR__INVALID_SYMBOL = 0x1771; // 6001
/** InvalidUri: Invalid metadata URI */
export const STABLECOIN_ERROR__INVALID_URI = 0x1772; // 6002
/** InvalidDecimals: Invalid decimal precision */
export const STABLECOIN_ERROR__INVALID_DECIMALS = 0x1773; // 6003
/** ZeroAmount: Amount must be greater than zero */
export const STABLECOIN_ERROR__ZERO_AMOUNT = 0x1774; // 6004
/** InvalidPresetConfiguration: Transfer hook requires permanent delegate */
export const STABLECOIN_ERROR__INVALID_PRESET_CONFIGURATION = 0x1775; // 6005
/** ComplianceNotEnabled: Compliance features are not enabled for this mint */
export const STABLECOIN_ERROR__COMPLIANCE_NOT_ENABLED = 0x1776; // 6006
/** PermanentDelegateNotEnabled: Permanent delegate is not enabled for this mint */
export const STABLECOIN_ERROR__PERMANENT_DELEGATE_NOT_ENABLED = 0x1777; // 6007
/** TransferHookNotEnabled: Transfer hook is not enabled for this mint */
export const STABLECOIN_ERROR__TRANSFER_HOOK_NOT_ENABLED = 0x1778; // 6008
/** NotMasterAuthority: Only the master authority can perform this action */
export const STABLECOIN_ERROR__NOT_MASTER_AUTHORITY = 0x1779; // 6009
/** NotActiveMinter: Caller is not an active minter for this mint */
export const STABLECOIN_ERROR__NOT_ACTIVE_MINTER = 0x177a; // 6010
/** NotBurner: Caller is not allowed to burn */
export const STABLECOIN_ERROR__NOT_BURNER = 0x177b; // 6011
/** NotPauser: Caller is not allowed to pause or freeze */
export const STABLECOIN_ERROR__NOT_PAUSER = 0x177c; // 6012
/** NotBlacklister: Caller is not allowed to manage the blacklist */
export const STABLECOIN_ERROR__NOT_BLACKLISTER = 0x177d; // 6013
/** NotSeizer: Caller is not allowed to seize tokens */
export const STABLECOIN_ERROR__NOT_SEIZER = 0x177e; // 6014
/** MintQuotaExceeded: Mint quota exceeded */
export const STABLECOIN_ERROR__MINT_QUOTA_EXCEEDED = 0x177f; // 6015
/** StablecoinPaused: This mint is currently paused */
export const STABLECOIN_ERROR__STABLECOIN_PAUSED = 0x1780; // 6016
/** AlreadyBlacklisted: Blacklist entry already exists */
export const STABLECOIN_ERROR__ALREADY_BLACKLISTED = 0x1781; // 6017
/** NotBlacklisted: Blacklist entry does not exist */
export const STABLECOIN_ERROR__NOT_BLACKLISTED = 0x1782; // 6018
/** TargetAccountNotFrozen: Target token account must be frozen before seizure */
export const STABLECOIN_ERROR__TARGET_ACCOUNT_NOT_FROZEN = 0x1783; // 6019
/** InvalidTreasuryAccount: Destination treasury account must be owned by the current authority */
export const STABLECOIN_ERROR__INVALID_TREASURY_ACCOUNT = 0x1784; // 6020
/** InvalidBlacklistTarget: Source token account owner does not match the blacklist entry */
export const STABLECOIN_ERROR__INVALID_BLACKLIST_TARGET = 0x1785; // 6021
/** InvalidMint: Mint account does not match configuration */
export const STABLECOIN_ERROR__INVALID_MINT = 0x1786; // 6022
/** MissingTransferHookProgram: Transfer hook program account is missing */
export const STABLECOIN_ERROR__MISSING_TRANSFER_HOOK_PROGRAM = 0x1787; // 6023
/** MissingExtraAccountMetaList: Extra account meta list account is missing */
export const STABLECOIN_ERROR__MISSING_EXTRA_ACCOUNT_META_LIST = 0x1788; // 6024
/** InvalidTransferHookProgram: Provided transfer hook program does not match the expected program */
export const STABLECOIN_ERROR__INVALID_TRANSFER_HOOK_PROGRAM = 0x1789; // 6025
/** Overflow: Math overflow */
export const STABLECOIN_ERROR__OVERFLOW = 0x178a; // 6026
/** InvalidAuthority: Invalid authority: cannot use system program or default pubkey */
export const STABLECOIN_ERROR__INVALID_AUTHORITY = 0x178b; // 6027
/** CannotBlacklistTreasury: Cannot blacklist the treasury (config authority) */
export const STABLECOIN_ERROR__CANNOT_BLACKLIST_TREASURY = 0x178c; // 6028
/** InvalidRole: Invalid role: cannot use system program or default pubkey */
export const STABLECOIN_ERROR__INVALID_ROLE = 0x178d; // 6029

export type StablecoinError =
  | typeof STABLECOIN_ERROR__ALREADY_BLACKLISTED
  | typeof STABLECOIN_ERROR__CANNOT_BLACKLIST_TREASURY
  | typeof STABLECOIN_ERROR__COMPLIANCE_NOT_ENABLED
  | typeof STABLECOIN_ERROR__INVALID_AUTHORITY
  | typeof STABLECOIN_ERROR__INVALID_BLACKLIST_TARGET
  | typeof STABLECOIN_ERROR__INVALID_DECIMALS
  | typeof STABLECOIN_ERROR__INVALID_MINT
  | typeof STABLECOIN_ERROR__INVALID_NAME
  | typeof STABLECOIN_ERROR__INVALID_PRESET_CONFIGURATION
  | typeof STABLECOIN_ERROR__INVALID_ROLE
  | typeof STABLECOIN_ERROR__INVALID_SYMBOL
  | typeof STABLECOIN_ERROR__INVALID_TRANSFER_HOOK_PROGRAM
  | typeof STABLECOIN_ERROR__INVALID_TREASURY_ACCOUNT
  | typeof STABLECOIN_ERROR__INVALID_URI
  | typeof STABLECOIN_ERROR__MINT_QUOTA_EXCEEDED
  | typeof STABLECOIN_ERROR__MISSING_EXTRA_ACCOUNT_META_LIST
  | typeof STABLECOIN_ERROR__MISSING_TRANSFER_HOOK_PROGRAM
  | typeof STABLECOIN_ERROR__NOT_ACTIVE_MINTER
  | typeof STABLECOIN_ERROR__NOT_BLACKLISTED
  | typeof STABLECOIN_ERROR__NOT_BLACKLISTER
  | typeof STABLECOIN_ERROR__NOT_BURNER
  | typeof STABLECOIN_ERROR__NOT_MASTER_AUTHORITY
  | typeof STABLECOIN_ERROR__NOT_PAUSER
  | typeof STABLECOIN_ERROR__NOT_SEIZER
  | typeof STABLECOIN_ERROR__OVERFLOW
  | typeof STABLECOIN_ERROR__PERMANENT_DELEGATE_NOT_ENABLED
  | typeof STABLECOIN_ERROR__STABLECOIN_PAUSED
  | typeof STABLECOIN_ERROR__TARGET_ACCOUNT_NOT_FROZEN
  | typeof STABLECOIN_ERROR__TRANSFER_HOOK_NOT_ENABLED
  | typeof STABLECOIN_ERROR__ZERO_AMOUNT;

let stablecoinErrorMessages: Record<StablecoinError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  stablecoinErrorMessages = {
    [STABLECOIN_ERROR__ALREADY_BLACKLISTED]: `Blacklist entry already exists`,
    [STABLECOIN_ERROR__CANNOT_BLACKLIST_TREASURY]: `Cannot blacklist the treasury (config authority)`,
    [STABLECOIN_ERROR__COMPLIANCE_NOT_ENABLED]: `Compliance features are not enabled for this mint`,
    [STABLECOIN_ERROR__INVALID_AUTHORITY]: `Invalid authority: cannot use system program or default pubkey`,
    [STABLECOIN_ERROR__INVALID_BLACKLIST_TARGET]: `Source token account owner does not match the blacklist entry`,
    [STABLECOIN_ERROR__INVALID_DECIMALS]: `Invalid decimal precision`,
    [STABLECOIN_ERROR__INVALID_MINT]: `Mint account does not match configuration`,
    [STABLECOIN_ERROR__INVALID_NAME]: `Invalid stablecoin name`,
    [STABLECOIN_ERROR__INVALID_PRESET_CONFIGURATION]: `Transfer hook requires permanent delegate`,
    [STABLECOIN_ERROR__INVALID_ROLE]: `Invalid role: cannot use system program or default pubkey`,
    [STABLECOIN_ERROR__INVALID_SYMBOL]: `Invalid stablecoin symbol`,
    [STABLECOIN_ERROR__INVALID_TRANSFER_HOOK_PROGRAM]: `Provided transfer hook program does not match the expected program`,
    [STABLECOIN_ERROR__INVALID_TREASURY_ACCOUNT]: `Destination treasury account must be owned by the current authority`,
    [STABLECOIN_ERROR__INVALID_URI]: `Invalid metadata URI`,
    [STABLECOIN_ERROR__MINT_QUOTA_EXCEEDED]: `Mint quota exceeded`,
    [STABLECOIN_ERROR__MISSING_EXTRA_ACCOUNT_META_LIST]: `Extra account meta list account is missing`,
    [STABLECOIN_ERROR__MISSING_TRANSFER_HOOK_PROGRAM]: `Transfer hook program account is missing`,
    [STABLECOIN_ERROR__NOT_ACTIVE_MINTER]: `Caller is not an active minter for this mint`,
    [STABLECOIN_ERROR__NOT_BLACKLISTED]: `Blacklist entry does not exist`,
    [STABLECOIN_ERROR__NOT_BLACKLISTER]: `Caller is not allowed to manage the blacklist`,
    [STABLECOIN_ERROR__NOT_BURNER]: `Caller is not allowed to burn`,
    [STABLECOIN_ERROR__NOT_MASTER_AUTHORITY]: `Only the master authority can perform this action`,
    [STABLECOIN_ERROR__NOT_PAUSER]: `Caller is not allowed to pause or freeze`,
    [STABLECOIN_ERROR__NOT_SEIZER]: `Caller is not allowed to seize tokens`,
    [STABLECOIN_ERROR__OVERFLOW]: `Math overflow`,
    [STABLECOIN_ERROR__PERMANENT_DELEGATE_NOT_ENABLED]: `Permanent delegate is not enabled for this mint`,
    [STABLECOIN_ERROR__STABLECOIN_PAUSED]: `This mint is currently paused`,
    [STABLECOIN_ERROR__TARGET_ACCOUNT_NOT_FROZEN]: `Target token account must be frozen before seizure`,
    [STABLECOIN_ERROR__TRANSFER_HOOK_NOT_ENABLED]: `Transfer hook is not enabled for this mint`,
    [STABLECOIN_ERROR__ZERO_AMOUNT]: `Amount must be greater than zero`,
  };
}

export function getStablecoinErrorMessage(code: StablecoinError): string {
  if (process.env.NODE_ENV !== "production") {
    return (stablecoinErrorMessages as Record<StablecoinError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isStablecoinError<TProgramErrorCode extends StablecoinError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    STABLECOIN_PROGRAM_ADDRESS,
    code,
  );
}
