/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithPayer,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfPlanAndSendFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/program-client-core";
import {
  getInitializeExtraAccountMetaListInstructionAsync,
  getTransferHookInstructionAsync,
  parseInitializeExtraAccountMetaListInstruction,
  parseTransferHookInstructionItem,
  type InitializeExtraAccountMetaListAsyncInput,
  type ParsedInitializeExtraAccountMetaListInstruction,
  type ParsedTransferHookInstructionItem,
  type TransferHookAsyncInput,
} from "../instructions";

export const TRANSFER_HOOK_PROGRAM_ADDRESS =
  "6QNzPyTwg2MH778GL8idYiU3teFJiuQx6R5L7xdU17KC" as Address<"6QNzPyTwg2MH778GL8idYiU3teFJiuQx6R5L7xdU17KC">;

export enum TransferHookInstruction {
  InitializeExtraAccountMetaList,
  TransferHook,
}

export function identifyTransferHookInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): TransferHookInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([43, 34, 13, 49, 167, 88, 235, 235]),
      ),
      0,
    )
  ) {
    return TransferHookInstruction.InitializeExtraAccountMetaList;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([105, 37, 101, 197, 75, 251, 102, 26]),
      ),
      0,
    )
  ) {
    return TransferHookInstruction.TransferHook;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "transferHook" },
  );
}

export type ParsedTransferHookInstruction<
  TProgram extends string = "6QNzPyTwg2MH778GL8idYiU3teFJiuQx6R5L7xdU17KC",
> =
  | ({
      instructionType: TransferHookInstruction.InitializeExtraAccountMetaList;
    } & ParsedInitializeExtraAccountMetaListInstruction<TProgram>)
  | ({
      instructionType: TransferHookInstruction.TransferHook;
    } & ParsedTransferHookInstructionItem<TProgram>);

export function parseTransferHookInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedTransferHookInstruction<TProgram> {
  const instructionType = identifyTransferHookInstruction(instruction);
  switch (instructionType) {
    case TransferHookInstruction.InitializeExtraAccountMetaList: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: TransferHookInstruction.InitializeExtraAccountMetaList,
        ...parseInitializeExtraAccountMetaListInstruction(instruction),
      };
    }
    case TransferHookInstruction.TransferHook: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: TransferHookInstruction.TransferHook,
        ...parseTransferHookInstructionItem(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        {
          instructionType: instructionType as string,
          programName: "transferHook",
        },
      );
  }
}

export type TransferHookPlugin = {
  instructions: TransferHookPluginInstructions;
};

export type TransferHookPluginInstructions = {
  initializeExtraAccountMetaList: (
    input: MakeOptional<InitializeExtraAccountMetaListAsyncInput, "payer">,
  ) => ReturnType<typeof getInitializeExtraAccountMetaListInstructionAsync> &
    SelfPlanAndSendFunctions;
  transferHook: (
    input: TransferHookAsyncInput,
  ) => ReturnType<typeof getTransferHookInstructionAsync> &
    SelfPlanAndSendFunctions;
};

export type TransferHookPluginRequirements = ClientWithPayer &
  ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function transferHookProgram() {
  return <T extends TransferHookPluginRequirements>(client: T) => {
    return {
      ...client,
      transferHook: <TransferHookPlugin>{
        instructions: {
          initializeExtraAccountMetaList: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializeExtraAccountMetaListInstructionAsync({
                ...input,
                payer: input.payer ?? client.payer,
              }),
            ),
          transferHook: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getTransferHookInstructionAsync(input),
            ),
        },
      },
    };
  };
}

type MakeOptional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;
