/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { TRANSFER_HOOK_PROGRAM_ADDRESS } from "../programs";

export const INITIALIZE_HOOK_CONFIG_DISCRIMINATOR = new Uint8Array([
  144, 239, 17, 85, 228, 48, 54, 43,
]);

export function getInitializeHookConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_HOOK_CONFIG_DISCRIMINATOR,
  );
}

export type InitializeHookConfigInstruction<
  TProgram extends string = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountHookConfig extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountHookConfig extends string
        ? WritableAccount<TAccountHookConfig>
        : TAccountHookConfig,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeHookConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  stablecoinProgramId: Address;
};

export type InitializeHookConfigInstructionDataArgs = {
  stablecoinProgramId: Address;
};

export function getInitializeHookConfigInstructionDataEncoder(): FixedSizeEncoder<InitializeHookConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["stablecoinProgramId", getAddressEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_HOOK_CONFIG_DISCRIMINATOR,
    }),
  );
}

export function getInitializeHookConfigInstructionDataDecoder(): FixedSizeDecoder<InitializeHookConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["stablecoinProgramId", getAddressDecoder()],
  ]);
}

export function getInitializeHookConfigInstructionDataCodec(): FixedSizeCodec<
  InitializeHookConfigInstructionDataArgs,
  InitializeHookConfigInstructionData
> {
  return combineCodec(
    getInitializeHookConfigInstructionDataEncoder(),
    getInitializeHookConfigInstructionDataDecoder(),
  );
}

export type InitializeHookConfigAsyncInput<
  TAccountPayer extends string = string,
  TAccountHookConfig extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  hookConfig?: Address<TAccountHookConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  stablecoinProgramId: InitializeHookConfigInstructionDataArgs["stablecoinProgramId"];
};

export async function getInitializeHookConfigInstructionAsync<
  TAccountPayer extends string,
  TAccountHookConfig extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
>(
  input: InitializeHookConfigAsyncInput<
    TAccountPayer,
    TAccountHookConfig,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializeHookConfigInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHookConfig,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRANSFER_HOOK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    hookConfig: { value: input.hookConfig ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.hookConfig.value) {
    accounts.hookConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([104, 111, 111, 107, 95, 99, 111, 110, 102, 105, 103]),
        ),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("hookConfig", accounts.hookConfig),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitializeHookConfigInstructionDataEncoder().encode(
      args as InitializeHookConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitializeHookConfigInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHookConfig,
    TAccountSystemProgram
  >);
}

export type InitializeHookConfigInput<
  TAccountPayer extends string = string,
  TAccountHookConfig extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  payer: TransactionSigner<TAccountPayer>;
  hookConfig: Address<TAccountHookConfig>;
  systemProgram?: Address<TAccountSystemProgram>;
  stablecoinProgramId: InitializeHookConfigInstructionDataArgs["stablecoinProgramId"];
};

export function getInitializeHookConfigInstruction<
  TAccountPayer extends string,
  TAccountHookConfig extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
>(
  input: InitializeHookConfigInput<
    TAccountPayer,
    TAccountHookConfig,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializeHookConfigInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountHookConfig,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRANSFER_HOOK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    hookConfig: { value: input.hookConfig ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("hookConfig", accounts.hookConfig),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitializeHookConfigInstructionDataEncoder().encode(
      args as InitializeHookConfigInstructionDataArgs,
    ),
    programAddress,
  } as InitializeHookConfigInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountHookConfig,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeHookConfigInstruction<
  TProgram extends string = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    hookConfig: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: InitializeHookConfigInstructionData;
};

export function parseInitializeHookConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializeHookConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      hookConfig: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeHookConfigInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
