/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { TRANSFER_HOOK_PROGRAM_ADDRESS } from "../programs";

export const TRANSFER_HOOK_DISCRIMINATOR = new Uint8Array([
  105, 37, 101, 197, 75, 251, 102, 26,
]);

export function getTransferHookDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSFER_HOOK_DISCRIMINATOR,
  );
}

export type TransferHookInstructionItem<
  TProgram extends string = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
  TAccountSource extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountDestination extends string | AccountMeta<string> = string,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountExtraAccountMetaList extends string | AccountMeta<string> = string,
  TAccountTransferHookProgram extends string | AccountMeta<string> = string,
  TAccountHookConfig extends string | AccountMeta<string> = string,
  TAccountStablecoinProgram extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountSourceBlacklist extends string | AccountMeta<string> = string,
  TAccountDestinationBlacklist extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSource extends string
        ? ReadonlyAccount<TAccountSource>
        : TAccountSource,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountDestination extends string
        ? ReadonlyAccount<TAccountDestination>
        : TAccountDestination,
      TAccountAuthority extends string
        ? ReadonlyAccount<TAccountAuthority>
        : TAccountAuthority,
      TAccountExtraAccountMetaList extends string
        ? ReadonlyAccount<TAccountExtraAccountMetaList>
        : TAccountExtraAccountMetaList,
      TAccountTransferHookProgram extends string
        ? ReadonlyAccount<TAccountTransferHookProgram>
        : TAccountTransferHookProgram,
      TAccountHookConfig extends string
        ? ReadonlyAccount<TAccountHookConfig>
        : TAccountHookConfig,
      TAccountStablecoinProgram extends string
        ? ReadonlyAccount<TAccountStablecoinProgram>
        : TAccountStablecoinProgram,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountSourceBlacklist extends string
        ? ReadonlyAccount<TAccountSourceBlacklist>
        : TAccountSourceBlacklist,
      TAccountDestinationBlacklist extends string
        ? ReadonlyAccount<TAccountDestinationBlacklist>
        : TAccountDestinationBlacklist,
      ...TRemainingAccounts,
    ]
  >;

export type TransferHookInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type TransferHookInstructionDataArgs = { amount: number | bigint };

export function getTransferHookInstructionDataEncoder(): FixedSizeEncoder<TransferHookInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: TRANSFER_HOOK_DISCRIMINATOR }),
  );
}

export function getTransferHookInstructionDataDecoder(): FixedSizeDecoder<TransferHookInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getTransferHookInstructionDataCodec(): FixedSizeCodec<
  TransferHookInstructionDataArgs,
  TransferHookInstructionData
> {
  return combineCodec(
    getTransferHookInstructionDataEncoder(),
    getTransferHookInstructionDataDecoder(),
  );
}

export type TransferHookAsyncInput<
  TAccountSource extends string = string,
  TAccountMint extends string = string,
  TAccountDestination extends string = string,
  TAccountAuthority extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountTransferHookProgram extends string = string,
  TAccountHookConfig extends string = string,
  TAccountStablecoinProgram extends string = string,
  TAccountConfig extends string = string,
  TAccountSourceBlacklist extends string = string,
  TAccountDestinationBlacklist extends string = string,
> = {
  source: Address<TAccountSource>;
  mint: Address<TAccountMint>;
  destination: Address<TAccountDestination>;
  authority: Address<TAccountAuthority>;
  extraAccountMetaList?: Address<TAccountExtraAccountMetaList>;
  transferHookProgram: Address<TAccountTransferHookProgram>;
  hookConfig?: Address<TAccountHookConfig>;
  stablecoinProgram: Address<TAccountStablecoinProgram>;
  config: Address<TAccountConfig>;
  sourceBlacklist: Address<TAccountSourceBlacklist>;
  destinationBlacklist: Address<TAccountDestinationBlacklist>;
  amount: TransferHookInstructionDataArgs["amount"];
};

export async function getTransferHookInstructionAsync<
  TAccountSource extends string,
  TAccountMint extends string,
  TAccountDestination extends string,
  TAccountAuthority extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountTransferHookProgram extends string,
  TAccountHookConfig extends string,
  TAccountStablecoinProgram extends string,
  TAccountConfig extends string,
  TAccountSourceBlacklist extends string,
  TAccountDestinationBlacklist extends string,
  TProgramAddress extends Address = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
>(
  input: TransferHookAsyncInput<
    TAccountSource,
    TAccountMint,
    TAccountDestination,
    TAccountAuthority,
    TAccountExtraAccountMetaList,
    TAccountTransferHookProgram,
    TAccountHookConfig,
    TAccountStablecoinProgram,
    TAccountConfig,
    TAccountSourceBlacklist,
    TAccountDestinationBlacklist
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  TransferHookInstructionItem<
    TProgramAddress,
    TAccountSource,
    TAccountMint,
    TAccountDestination,
    TAccountAuthority,
    TAccountExtraAccountMetaList,
    TAccountTransferHookProgram,
    TAccountHookConfig,
    TAccountStablecoinProgram,
    TAccountConfig,
    TAccountSourceBlacklist,
    TAccountDestinationBlacklist
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRANSFER_HOOK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    source: { value: input.source ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    destination: { value: input.destination ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: false },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: false,
    },
    transferHookProgram: {
      value: input.transferHookProgram ?? null,
      isWritable: false,
    },
    hookConfig: { value: input.hookConfig ?? null, isWritable: false },
    stablecoinProgram: {
      value: input.stablecoinProgram ?? null,
      isWritable: false,
    },
    config: { value: input.config ?? null, isWritable: false },
    sourceBlacklist: {
      value: input.sourceBlacklist ?? null,
      isWritable: false,
    },
    destinationBlacklist: {
      value: input.destinationBlacklist ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.extraAccountMetaList.value) {
    accounts.extraAccountMetaList.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            101, 120, 116, 114, 97, 45, 97, 99, 99, 111, 117, 110, 116, 45, 109,
            101, 116, 97, 115,
          ]),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount("mint", accounts.mint.value),
        ),
      ],
    });
  }
  if (!accounts.hookConfig.value) {
    accounts.hookConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([104, 111, 111, 107, 95, 99, 111, 110, 102, 105, 103]),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("source", accounts.source),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("destination", accounts.destination),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("extraAccountMetaList", accounts.extraAccountMetaList),
      getAccountMeta("transferHookProgram", accounts.transferHookProgram),
      getAccountMeta("hookConfig", accounts.hookConfig),
      getAccountMeta("stablecoinProgram", accounts.stablecoinProgram),
      getAccountMeta("config", accounts.config),
      getAccountMeta("sourceBlacklist", accounts.sourceBlacklist),
      getAccountMeta("destinationBlacklist", accounts.destinationBlacklist),
    ],
    data: getTransferHookInstructionDataEncoder().encode(
      args as TransferHookInstructionDataArgs,
    ),
    programAddress,
  } as TransferHookInstructionItem<
    TProgramAddress,
    TAccountSource,
    TAccountMint,
    TAccountDestination,
    TAccountAuthority,
    TAccountExtraAccountMetaList,
    TAccountTransferHookProgram,
    TAccountHookConfig,
    TAccountStablecoinProgram,
    TAccountConfig,
    TAccountSourceBlacklist,
    TAccountDestinationBlacklist
  >);
}

export type TransferHookInput<
  TAccountSource extends string = string,
  TAccountMint extends string = string,
  TAccountDestination extends string = string,
  TAccountAuthority extends string = string,
  TAccountExtraAccountMetaList extends string = string,
  TAccountTransferHookProgram extends string = string,
  TAccountHookConfig extends string = string,
  TAccountStablecoinProgram extends string = string,
  TAccountConfig extends string = string,
  TAccountSourceBlacklist extends string = string,
  TAccountDestinationBlacklist extends string = string,
> = {
  source: Address<TAccountSource>;
  mint: Address<TAccountMint>;
  destination: Address<TAccountDestination>;
  authority: Address<TAccountAuthority>;
  extraAccountMetaList: Address<TAccountExtraAccountMetaList>;
  transferHookProgram: Address<TAccountTransferHookProgram>;
  hookConfig: Address<TAccountHookConfig>;
  stablecoinProgram: Address<TAccountStablecoinProgram>;
  config: Address<TAccountConfig>;
  sourceBlacklist: Address<TAccountSourceBlacklist>;
  destinationBlacklist: Address<TAccountDestinationBlacklist>;
  amount: TransferHookInstructionDataArgs["amount"];
};

export function getTransferHookInstruction<
  TAccountSource extends string,
  TAccountMint extends string,
  TAccountDestination extends string,
  TAccountAuthority extends string,
  TAccountExtraAccountMetaList extends string,
  TAccountTransferHookProgram extends string,
  TAccountHookConfig extends string,
  TAccountStablecoinProgram extends string,
  TAccountConfig extends string,
  TAccountSourceBlacklist extends string,
  TAccountDestinationBlacklist extends string,
  TProgramAddress extends Address = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
>(
  input: TransferHookInput<
    TAccountSource,
    TAccountMint,
    TAccountDestination,
    TAccountAuthority,
    TAccountExtraAccountMetaList,
    TAccountTransferHookProgram,
    TAccountHookConfig,
    TAccountStablecoinProgram,
    TAccountConfig,
    TAccountSourceBlacklist,
    TAccountDestinationBlacklist
  >,
  config?: { programAddress?: TProgramAddress },
): TransferHookInstructionItem<
  TProgramAddress,
  TAccountSource,
  TAccountMint,
  TAccountDestination,
  TAccountAuthority,
  TAccountExtraAccountMetaList,
  TAccountTransferHookProgram,
  TAccountHookConfig,
  TAccountStablecoinProgram,
  TAccountConfig,
  TAccountSourceBlacklist,
  TAccountDestinationBlacklist
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRANSFER_HOOK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    source: { value: input.source ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    destination: { value: input.destination ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: false },
    extraAccountMetaList: {
      value: input.extraAccountMetaList ?? null,
      isWritable: false,
    },
    transferHookProgram: {
      value: input.transferHookProgram ?? null,
      isWritable: false,
    },
    hookConfig: { value: input.hookConfig ?? null, isWritable: false },
    stablecoinProgram: {
      value: input.stablecoinProgram ?? null,
      isWritable: false,
    },
    config: { value: input.config ?? null, isWritable: false },
    sourceBlacklist: {
      value: input.sourceBlacklist ?? null,
      isWritable: false,
    },
    destinationBlacklist: {
      value: input.destinationBlacklist ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("source", accounts.source),
      getAccountMeta("mint", accounts.mint),
      getAccountMeta("destination", accounts.destination),
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("extraAccountMetaList", accounts.extraAccountMetaList),
      getAccountMeta("transferHookProgram", accounts.transferHookProgram),
      getAccountMeta("hookConfig", accounts.hookConfig),
      getAccountMeta("stablecoinProgram", accounts.stablecoinProgram),
      getAccountMeta("config", accounts.config),
      getAccountMeta("sourceBlacklist", accounts.sourceBlacklist),
      getAccountMeta("destinationBlacklist", accounts.destinationBlacklist),
    ],
    data: getTransferHookInstructionDataEncoder().encode(
      args as TransferHookInstructionDataArgs,
    ),
    programAddress,
  } as TransferHookInstructionItem<
    TProgramAddress,
    TAccountSource,
    TAccountMint,
    TAccountDestination,
    TAccountAuthority,
    TAccountExtraAccountMetaList,
    TAccountTransferHookProgram,
    TAccountHookConfig,
    TAccountStablecoinProgram,
    TAccountConfig,
    TAccountSourceBlacklist,
    TAccountDestinationBlacklist
  >);
}

export type ParsedTransferHookInstructionItem<
  TProgram extends string = typeof TRANSFER_HOOK_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    source: TAccountMetas[0];
    mint: TAccountMetas[1];
    destination: TAccountMetas[2];
    authority: TAccountMetas[3];
    extraAccountMetaList: TAccountMetas[4];
    transferHookProgram: TAccountMetas[5];
    hookConfig: TAccountMetas[6];
    stablecoinProgram: TAccountMetas[7];
    config: TAccountMetas[8];
    sourceBlacklist: TAccountMetas[9];
    destinationBlacklist: TAccountMetas[10];
  };
  data: TransferHookInstructionData;
};

export function parseTransferHookInstructionItem<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedTransferHookInstructionItem<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 11,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      source: getNextAccount(),
      mint: getNextAccount(),
      destination: getNextAccount(),
      authority: getNextAccount(),
      extraAccountMetaList: getNextAccount(),
      transferHookProgram: getNextAccount(),
      hookConfig: getNextAccount(),
      stablecoinProgram: getNextAccount(),
      config: getNextAccount(),
      sourceBlacklist: getNextAccount(),
      destinationBlacklist: getNextAccount(),
    },
    data: getTransferHookInstructionDataDecoder().decode(instruction.data),
  };
}
